stopifnot(Sys.getenv("_R_CHECK_PACKAGE_NAME_") == "drmcheckprobe", !interactive())
Sys.unsetenv(c("NOT_CRAN", "DRMTMB_JULIA_TESTS"))
e <- new.env(parent=globalenv())
forms <- parse("/private/tmp/drm-parity-20260830/drmTMB/R/julia-bridge.R")
for (f in forms) if (is.call(f) && identical(f[[1L]], as.name("<-")) && as.character(f[[2L]]) %in% c("drm_julia_cran_lane_blocked", "drm_julia_setup")) eval(f,e)
stopifnot(e$drm_julia_cran_lane_blocked())
msg <- tryCatch(e$drm_julia_setup(path="/does/not/exist"),error=conditionMessage)
stopifnot(grepl("Live Julia setup is disabled on the CRAN check lane",msg,fixed=TRUE))
cat("ACTUAL_R_CHECK_GUARD_PASS marker=",Sys.getenv("_R_CHECK_PACKAGE_NAME_"),"\n",sep="")
