# #1130: nlminb's `rel.tol`/`x.tol` stopping rules trigger on a relative
# change in the objective or the step, not on the gradient norm. On the
# varying-scale random-intercept fixture below (`bf(y ~ x + (1 | g), sigma ~
# x)`, 12 groups x 12 rows), nlminb reports "relative convergence" while the
# exact TMB outer gradient at that point is still far from zero (measured
# ~3.5e-4), moving fitted coefficients ~1e-5 from the true optimum -- invisible
# at the training rows but amplified at extrapolated newdata (the cross-engine
# parity cell that raised #1130). `drm_newton_polish()` (R/drmTMB.R) fixes this
# with a few Newton steps on the exact gradient and a finite-differenced
# Hessian of it, applied by default after every `nlminb()` fit. These tests are
# self-contained (no DRM.jl dependency): they check that the polished optimum
# is close to a much more tightly polished reference computed on this same
# fixture, and that the reported optimum is an actual stationary point of the
# TMB objective.
#
# Fixture: tests/testthat/fixtures/s10-varying-scale.csv, copied from DRM.jl
# branch fix/563-s10-lss-ranef-gtol @ 744d28b3
# (test/parity/lss-ranef-varying-scale/data.csv), the exact data.frame
# generated by:
#   set.seed(202608302L)
#   labels <- c("z","a","m","b","x","c","w","d","v","e","u","f")
#   g <- factor(rep(labels, each = 12L), levels = c("unused", rev(sort(labels))))
#   n <- length(g); x <- runif(n, -1, 1)
#   b <- setNames(rnorm(length(labels), sd = 0.8), labels)
#   y <- 0.3 + 0.6*x + b[as.character(g)] + rnorm(n, sd = exp(-0.5 + 0.15*x))
#   dat <- data.frame(y, x, g)[sample.int(n), , drop = FALSE]

s10_varying_scale_fixture <- function() {
  dat <- utils::read.csv(
    test_path("fixtures", "s10-varying-scale.csv"),
    stringsAsFactors = FALSE
  )
  labels <- c("z", "a", "m", "b", "x", "c", "w", "d", "v", "e", "u", "f")
  dat$g <- factor(dat$g, levels = c("unused", rev(sort(labels))))
  dat
}

# A reference optimum obtained by running `drm_newton_polish()` a second time
# on the package-default fit, with a far stricter gradient tolerance
# (`grad_tol = 1e-13`, `max_iter = 10`) than the package default
# (`grad_tol = 1e-8`, `max_iter = 3`). Measured 2026-09-03: the super-tight
# reference's max |gradient| is 2.99e-14 and it differs from the
# package-default polish by 7.25e-11 in parameter space (4.68e-11 at the
# extrapolated newdata point below) -- the two agree far inside every
# tolerance used here.
s10_reference_mu_newdata <- c(
  0.16723687209213173,
  0.54703874680876263,
  0.98109803219919800
)

test_that("optimizer polish reaches the true optimum within the parity tolerance (#1130)", {
  dat <- s10_varying_scale_fixture()
  fit <- drmTMB(bf(y ~ x + (1 | g), sigma ~ x), data = dat, engine = "tmb")

  grid <- data.frame(x = c(-0.7, 0, 0.8))
  mu_newdata <- predict(fit, newdata = grid, dpar = "mu", type = "link")

  expect_lt(max(abs(mu_newdata - s10_reference_mu_newdata)), 1e-6)
})

test_that("the reported optimum is a stationary point and further polish barely moves it (#1130)", {
  dat <- s10_varying_scale_fixture()
  fit <- drmTMB(bf(y ~ x + (1 | g), sigma ~ x), data = dat, engine = "tmb")

  grad <- as.numeric(fit$obj$gr(fit$opt$par))
  expect_lt(max(abs(grad)), 1e-6)

  # nlminb's own convergence code should have been overridden by the polish's
  # own gradient-based criterion, with an honest message pointing at it.
  expect_identical(fit$opt$convergence, 0L)
  expect_match(fit$opt$message, "Newton polish")

  # Self-consistency gate: tightening further (a much stricter grad_tol/
  # max_iter on top of the already-polished optimum) moves the estimates by
  # less than 1e-7 -- the reported optimum is not an artifact of the default
  # polish's own stopping tolerance.
  tighter <- drmTMB:::drm_newton_polish(
    fit$opt,
    fit$obj,
    grad_tol = 1e-12,
    max_iter = 5L
  )
  expect_lt(max(abs(tighter$par - fit$opt$par)), 1e-7)
})

test_that("newton_polish = FALSE restores the raw nlminb optimum (#1130)", {
  dat <- s10_varying_scale_fixture()
  fit_polished <- drmTMB(bf(y ~ x + (1 | g), sigma ~ x), data = dat, engine = "tmb")
  fit_raw <- drmTMB(
    bf(y ~ x + (1 | g), sigma ~ x),
    data = dat,
    engine = "tmb",
    control = drm_control(newton_polish = FALSE)
  )

  # The raw fit reports nlminb's own convergence code/message untouched.
  expect_identical(fit_raw$opt$convergence, 0L)
  expect_false(grepl("Newton polish", fit_raw$opt$message, fixed = TRUE))

  # The two optima differ by the same order of magnitude as the #1130 shortfall.
  expect_gt(max(abs(fit_raw$opt$par - fit_polished$opt$par)), 1e-6)
})
