test_that("AOI-3 private full-refit runner keeps its frozen execution boundary", {
  runner <- test_path("..", "..", "tools", "run-aoi3-bernoulli-nb2-full-refit.R")
  reducer <- test_path("..", "..", "tools", "summarize-aoi3-bernoulli-nb2-smoke.R")
  diagnostic_reducer <- test_path("..", "..", "tools", "summarize-aoi3r1-diagnostic-smoke.R")
  contract <- test_path("..", "..", "docs", "dev-log", "2026-07-31-aoi3-full-refit-calibration-contract.md")
  expect_silent(parse(file = runner))
  expect_silent(parse(file = reducer))
  expect_silent(parse(file = diagnostic_reducer))
  text <- paste(readLines(runner, warn = FALSE), collapse = "\n")
  expect_match(text, "drm_pair_general_eta_sandwich", fixed = TRUE)
  expect_match(text, "simulate_inner", fixed = TRUE)
  expect_match(text, "fit_complete", fixed = TRUE)
  expect_match(text, "outer-sandwich-covariance.csv", fixed = TRUE)

  inner_setup <- regexpr("row <- c(", text, fixed = TRUE)
  inherited_payload <- regexpr("row <- inherit_outer_payload(row, base)", text, fixed = TRUE)
  inner_eligibility <- regexpr("if (!is.null(fitted) && identical(base$outer_status, \"interior\") && identical(base$sandwich_status, \"ok\"))", text, fixed = TRUE)
  expect_gt(inner_setup, 0L)
  expect_gt(inherited_payload, 0L)
  expect_gt(inner_eligibility, 0L)
  expect_lt(inner_setup, inherited_payload)
  expect_lt(inherited_payload, inner_eligibility)
  expect_match(text, "if (!has_diagnostic_payload(outer)) return(row)", fixed = TRUE)
  expect_match(text, "diagnostic_payload_origin <- \"outer\"", fixed = TRUE)
  expect_match(text, "diagnostic_payload_origin <- \"inner\"", fixed = TRUE)
  expect_match(text, "diagnostic_eligibility_reason", fixed = TRUE)

  diagnostic_reducer_text <- paste(readLines(diagnostic_reducer, warn = FALSE), collapse = "\n")
  expect_match(diagnostic_reducer_text, "all(required_payload %in% names(inner))", fixed = TRUE)
  expect_match(diagnostic_reducer_text, "all(!is.na(inner$diagnostic_version))", fixed = TRUE)
  expect_match(diagnostic_reducer_text, "diagnostic_version", fixed = TRUE)
  contract_text <- paste(readLines(contract, warn = FALSE), collapse = "\n")
  expect_match(contract_text, "1,194,000", fixed = TRUE)
  expect_match(contract_text, "non-covering", fixed = TRUE)
  expect_match(contract_text, "AOI-2 point-recovery HOLD", fixed = TRUE)
})
