# The parity matrix (docs/design/parity-matrix.md, generated by
# tools/write-parity-matrix.R) joins the family REGISTRY to the bridge ledger
# TSV. Three things are pinned here (parity-joint A2, 2026-09-05):
#
#  (a) every route the bridge ADMITS has a TSV row. This test is RED by design
#      until the leaf that ledgers the unledgered routes lands (A3), and it is
#      the red control for any later leaf that admits a family (A4): a new
#      registry `fe` row without a TSV row fails here, naming the route.
#  (b) the `phylo_gamma_beta_binomial` naming trap: a reader that matches
#      capability_id substrings reports beta_binomial as covered while the
#      bridge refuses it. The matcher joins on the `syntax` column instead.
#  (c) regeneration is idempotent, and the committed artefact is current when
#      the DRM.jl clone at hand is at the pin the artefact names.
#
# The matcher below is a TWIN of the one in tools/write-parity-matrix.R --
# tools/ is .Rbuildignore'd, so the installed package cannot source it. The
# last test asserts the twins agree whenever the tool file is reachable.

pm_test_family_constructor <- function(family) {
  if (identical(family, "gamma")) "Gamma" else family
}

pm_test_modifier_dpars <- function() c("zi", "hu", "zoi", "coi")

pm_test_syntax_calls <- function(syntax, constructor) {
  grepl(paste0("(^|[^A-Za-z0-9_.])", constructor, "\\("), syntax, perl = TRUE)
}

pm_test_syntax_has_modifier <- function(syntax, dpar) {
  grepl(paste0("(^|[^A-Za-z0-9_.])", dpar, "\\s*(=\\s*)?~"), syntax, perl = TRUE)
}

pm_test_tsv_rows_for_family <- function(tsv, family, modifier = NULL) {
  hit <- tsv$route == "base" & pm_test_syntax_calls(tsv$syntax, pm_test_family_constructor(family))
  any_mod <- Reduce(`|`, lapply(pm_test_modifier_dpars(), function(d) pm_test_syntax_has_modifier(tsv$syntax, d)))
  has_re_term <- grepl("|", tsv$syntax, fixed = TRUE)
  if (is.null(modifier)) hit & !any_mod & !has_re_term else hit & pm_test_syntax_has_modifier(tsv$syntax, modifier)
}

# Native modifier model types as the BRIDGE spells them (hurdle NB2 reaches
# DRM.jl as nbinom2() + `hu ~`; native drmTMB spells it truncated_nbinom2()).
pm_test_modifier_routes <- function() {
  data.frame(
    model_type = c("zi_poisson", "zi_nbinom2", "hurdle_nbinom2"),
    native_family = c("poisson", "nbinom2", "truncated_nbinom2"),
    bridge_family = c("poisson", "nbinom2", "nbinom2"),
    modifier = c("zi", "zi", "hu"),
    stringsAsFactors = FALSE
  )
}

pm_test_admitted_routes <- function(registry, supported_dpars) {
  fe <- vapply(registry[vapply(registry, function(s) isTRUE(s$fe), logical(1L))], `[[`, character(1L), "family")
  routes <- data.frame(route = fe, family = fe, modifier = NA_character_, stringsAsFactors = FALSE)
  mods <- pm_test_modifier_routes()
  keep <- mods$bridge_family %in% fe & mods$modifier %in% supported_dpars
  if (any(keep)) {
    m <- mods[keep, , drop = FALSE]
    routes <- rbind(routes, data.frame(
      route = paste0(m$bridge_family, "+", m$modifier),
      family = m$bridge_family, modifier = m$modifier, stringsAsFactors = FALSE
    ))
  }
  rownames(routes) <- NULL
  routes
}

pm_test_routes_without_row <- function(routes, tsv) {
  covered <- vapply(seq_len(nrow(routes)), function(i) {
    mod <- if (is.na(routes$modifier[[i]])) NULL else routes$modifier[[i]]
    any(pm_test_tsv_rows_for_family(tsv, routes$family[[i]], mod))
  }, logical(1L))
  routes$route[!covered]
}

pm_test_read_tsv <- function() {
  path <- system.file("extdata", "julia-capabilities.tsv", package = "drmTMB")
  expect_true(nzchar(path))
  tab <- utils::read.delim(path, stringsAsFactors = FALSE, check.names = FALSE, quote = "", encoding = "UTF-8")
  tab[] <- lapply(tab, as.character)
  tab
}

pm_test_tool_path <- function() {
  # Only reachable from a source checkout (tools/ is .Rbuildignore'd).
  path <- testthat::test_path("..", "..", "tools", "write-parity-matrix.R")
  if (file.exists(path)) normalizePath(path) else ""
}

pm_test_source_tool <- function(path) {
  env <- new.env(parent = globalenv())
  sys.source(path, envir = env)
  env
}

test_that("every route the bridge admits has a TSV row (RED until the ledgering leaf lands)", {
  tsv <- pm_test_read_tsv()
  routes <- pm_test_admitted_routes(
    drmTMB:::drm_julia_family_registry(),
    drmTMB:::julia_bridge_supported_dpars()
  )
  # The enumeration is grounded in the bridge, not in this file: every route's
  # family is admitted by drm_julia_family_tag() and its modifier is marshalled.
  for (i in seq_len(nrow(routes))) {
    expect_identical(drmTMB:::drm_julia_family_tag(routes$family[[i]]), routes$family[[i]])
  }
  expect_true(all(is.na(routes$modifier) | routes$modifier %in% drmTMB:::julia_bridge_supported_dpars()))
  expect_gte(nrow(routes), 9L)

  missing <- pm_test_routes_without_row(routes, tsv)
  expect(
    length(missing) == 0L,
    sprintf(
      "%d of %d routes the bridge admits have NO row in julia-capabilities.tsv (route == \"base\" and syntax calling the family constructor%s): %s",
      length(missing), nrow(routes), " plus the modifier's `dpar ~` formula for a modifier route",
      paste(missing, collapse = ", ")
    )
  )
})

test_that("beta_binomial is NOT reported covered by the phylo_gamma_beta_binomial row", {
  tsv <- pm_test_read_tsv()
  trap <- tsv[tsv$capability_id == "phylo_gamma_beta_binomial", , drop = FALSE]
  expect_identical(nrow(trap), 1L)

  # POSITIVE CONTROL: the trap is real -- a capability_id substring reader
  # says beta_binomial has a row.
  expect_true(any(grepl("beta_binomial", tsv$capability_id, fixed = TRUE)))

  # The syntax join does not: the row's syntax calls Gamma(), beta() and
  # stats::binomial(), never beta_binomial().
  expect_true(pm_test_syntax_calls(trap$syntax, "Gamma"))
  expect_true(pm_test_syntax_calls(trap$syntax, "beta"))
  expect_true(pm_test_syntax_calls(trap$syntax, "binomial"))
  expect_false(pm_test_syntax_calls(trap$syntax, "beta_binomial"))
  expect_false(any(pm_test_tsv_rows_for_family(tsv, "beta_binomial")))

  # And the converse: a beta_binomial() call evidences neither beta nor binomial.
  bb <- "bf(y ~ x, sigma ~ 1), family = beta_binomial(), engine = \"julia\""
  expect_true(pm_test_syntax_calls(bb, "beta_binomial"))
  expect_false(pm_test_syntax_calls(bb, "beta"))
  expect_false(pm_test_syntax_calls(bb, "binomial"))

  # A ZIP row evidences the zi route, not plain Poisson.
  zip <- data.frame(route = "base", syntax = "bf(y ~ x, zi ~ x), family = poisson(), engine = \"julia\"", stringsAsFactors = FALSE)
  expect_true(pm_test_tsv_rows_for_family(zip, "poisson", "zi"))
  expect_false(pm_test_tsv_rows_for_family(zip, "poisson"))

  # The bridge refuses beta_binomial today; a registry row for it must arrive
  # together with a TSV row whose syntax calls beta_binomial(), or test (a) fails.
  expect_error(drmTMB:::drm_julia_family_tag("beta_binomial"), "currently supports Workflow G")
})

test_that("an ordinary random-effect TSV row is not absorbed by the plain fixed-effect family match", {
  # RED CONTROL for this guard: without the `|` exclusion, `gaussian` with no
  # modifier matches base_gaussian_location_scale AND the three ordinary-RE
  # rows A5 ledgered (route == "base", syntax calls gaussian(), no zi/hu/zoi/coi
  # formula -- but a `(1 | g)` term instead). The plain family route must match
  # exactly the one fixed-effect-only row.
  tsv <- pm_test_read_tsv()
  hit <- pm_test_tsv_rows_for_family(tsv, "gaussian")
  expect_identical(tsv$capability_id[hit], "base_gaussian_location_scale")
  re_ids <- c("gaussian_random_intercept_mu", "gaussian_random_slope_mu", "gaussian_sigma_random_intercept")
  expect_true(all(re_ids %in% tsv$capability_id))
  expect_false(any(tsv$capability_id[hit] %in% re_ids))
})

test_that("tools/write-parity-matrix.R regenerates byte-identically and matches the committed artefact at its pin", {
  tool <- pm_test_tool_path()
  skip_if(!nzchar(tool), "tools/write-parity-matrix.R is not reachable (installed package)")
  drmjl <- Sys.getenv("DRM_JL_PATH", unset = "")
  skip_if(!nzchar(drmjl) || !dir.exists(drmjl), "DRM_JL_PATH is not set to a DRM.jl clone")
  root <- normalizePath(testthat::test_path("..", ".."))

  env <- pm_test_source_tool(tool)
  out1 <- tempfile(fileext = ".md")
  out2 <- tempfile(fileext = ".md")
  suppressMessages(env$pm_write_matrix(root, drmjl, out1))
  suppressMessages(env$pm_write_matrix(root, drmjl, out2))
  expect_identical(readLines(out1, warn = FALSE), readLines(out2, warn = FALSE))

  gen <- readLines(out1, warn = FALSE)
  expect_true(any(grepl("^## The matrix$", gen)))
  n_rows <- sum(grepl("^\\| (GREEN )?`", gen))
  expect_identical(n_rows, nrow(env$pm_parse_status_table(readLines(file.path(root, "docs", "design", "capability-status.md"), warn = FALSE))))

  committed_path <- file.path(root, "docs", "design", "parity-matrix.md")
  expect_true(file.exists(committed_path))
  committed <- readLines(committed_path, warn = FALSE)
  pin_line <- grep("at pin `[0-9a-f]{40}`", committed, value = TRUE)
  expect_length(pin_line, 1L)
  committed_pin <- sub(".*at pin `([0-9a-f]{40})`.*", "\\1", pin_line)
  clone_pin <- env$pm_git(drmjl, "rev-parse", "HEAD")
  if (identical(clone_pin, committed_pin)) {
    expect_identical(gen, committed)
  } else {
    skip(sprintf("DRM.jl clone is at %s, committed artefact was generated at %s: currency not checked", substr(clone_pin, 1, 8), substr(committed_pin, 1, 8)))
  }
})

test_that("the test's matcher twin agrees with the tool's matcher", {
  tool <- pm_test_tool_path()
  skip_if(!nzchar(tool), "tools/write-parity-matrix.R is not reachable (installed package)")
  env <- pm_test_source_tool(tool)
  tsv <- pm_test_read_tsv()
  registry <- drmTMB:::drm_julia_family_registry()
  dpars <- drmTMB:::julia_bridge_supported_dpars()
  expect_identical(env$pm_modifier_routes(), pm_test_modifier_routes())
  expect_identical(env$pm_admitted_routes(registry, dpars), pm_test_admitted_routes(registry, dpars))
  routes <- pm_test_admitted_routes(registry, dpars)
  expect_identical(env$pm_routes_without_row(routes, tsv), pm_test_routes_without_row(routes, tsv))
  fams <- c(vapply(registry, `[[`, character(1L), "family"), "beta_binomial", "tweedie", "truncated_nbinom2")
  for (f in fams) {
    expect_identical(env$pm_tsv_rows_for_family(tsv, f), pm_test_tsv_rows_for_family(tsv, f), info = f)
    for (m in pm_test_modifier_dpars()) {
      expect_identical(env$pm_tsv_rows_for_family(tsv, f, m), pm_test_tsv_rows_for_family(tsv, f, m), info = paste(f, m))
    }
  }
})
