test_that('paired comparator re-verifier self-tests and fails closed on an empty archive store', {
  worker <- testthat::test_path('..', '..', 'tools', 'reverify-phylo-temporal-ou-comparator.R')
  self <- system2('Rscript', c('--vanilla', worker, '--self-test'), stdout = TRUE, stderr = TRUE)
  expect_null(attr(self, 'status'))
  expect_true(any(grepl('PHYLO_TEMPORAL_OU_COMPARATOR_REVERIFY_SELFTEST_PASS', self, fixed = TRUE)))
  campaign <- tempfile('comparator-empty-'); output <- tempfile('comparator-result-'); dir.create(campaign)
  on.exit(unlink(c(campaign, output), recursive = TRUE, force = TRUE), add = TRUE)
  bad <- suppressWarnings(system2('Rscript', c('--vanilla', worker, paste0('--campaign-dir=', campaign), paste0('--output-dir=', output)), stdout = TRUE, stderr = TRUE))
  expect_false(is.null(attr(bad, 'status')))
  expect_true(file.exists(file.path(output, 'task-inventory.csv')))
  text <- paste(readLines(worker, warn = FALSE), collapse = '\n')
  expect_false(grepl('drmTMB\\s*\\(', text))
  expect_true(grepl('sha256sum', text, fixed = TRUE))
})
