# #1130: nlminb's `rel.tol`/`x.tol` stopping rules trigger on a relative
# change in the objective or the step, not on the gradient norm. On the
# varying-scale random-intercept fixture below (`bf(y ~ x + (1 | g), sigma ~
# x)`, 12 groups x 12 rows), nlminb reports "relative convergence" while the
# exact TMB outer gradient at that point is still far from zero (measured
# ~3.5e-4), moving fitted coefficients ~1e-5 from the true optimum -- invisible
# at the training rows but amplified at extrapolated newdata (the cross-engine
# parity cell that raised #1130). `drm_newton_polish()` (R/drmTMB.R) fixes this
# with a few Newton steps on the exact gradient and a finite-differenced
# Hessian of it, applied by default after every `nlminb()` fit. These tests are
# self-contained (no DRM.jl dependency): they check that the polished optimum
# is close to a much more tightly polished reference computed on this same
# fixture, and that the reported optimum is an actual stationary point of the
# TMB objective.
#
# Fixture: tests/testthat/fixtures/s10-varying-scale.csv, copied from DRM.jl
# branch fix/563-s10-lss-ranef-gtol @ 744d28b3
# (test/parity/lss-ranef-varying-scale/data.csv), the exact data.frame
# generated by:
#   set.seed(202608302L)
#   labels <- c("z","a","m","b","x","c","w","d","v","e","u","f")
#   g <- factor(rep(labels, each = 12L), levels = c("unused", rev(sort(labels))))
#   n <- length(g); x <- runif(n, -1, 1)
#   b <- setNames(rnorm(length(labels), sd = 0.8), labels)
#   y <- 0.3 + 0.6*x + b[as.character(g)] + rnorm(n, sd = exp(-0.5 + 0.15*x))
#   dat <- data.frame(y, x, g)[sample.int(n), , drop = FALSE]

s10_varying_scale_fixture <- function() {
  dat <- utils::read.csv(
    test_path("fixtures", "s10-varying-scale.csv"),
    stringsAsFactors = FALSE
  )
  labels <- c("z", "a", "m", "b", "x", "c", "w", "d", "v", "e", "u", "f")
  dat$g <- factor(dat$g, levels = c("unused", rev(sort(labels))))
  dat
}

# A reference optimum obtained by running `drm_newton_polish()` a second time
# on the package-default fit, with a far stricter gradient tolerance
# (`grad_tol = 1e-13`, `max_iter = 10`) than the package default
# (`grad_tol = 1e-8`, `max_iter = 3`). Measured 2026-09-03: the super-tight
# reference's max |gradient| is 2.99e-14 and it differs from the
# package-default polish by 7.25e-11 in parameter space (4.68e-11 at the
# extrapolated newdata point below) -- the two agree far inside every
# tolerance used here.
s10_reference_mu_newdata <- c(
  0.16723687209213173,
  0.54703874680876263,
  0.98109803219919800
)

test_that("optimizer polish reaches the true optimum within the parity tolerance (#1130)", {
  dat <- s10_varying_scale_fixture()
  fit <- drmTMB(bf(y ~ x + (1 | g), sigma ~ x), data = dat, engine = "tmb")

  grid <- data.frame(x = c(-0.7, 0, 0.8))
  mu_newdata <- predict(fit, newdata = grid, dpar = "mu", type = "link")

  expect_lt(max(abs(mu_newdata - s10_reference_mu_newdata)), 1e-6)
})

test_that("the reported optimum is a stationary point and further polish barely moves it (#1130)", {
  dat <- s10_varying_scale_fixture()
  fit <- drmTMB(bf(y ~ x + (1 | g), sigma ~ x), data = dat, engine = "tmb")

  grad <- as.numeric(fit$obj$gr(fit$opt$par))
  expect_lt(max(abs(grad)), 1e-6)

  # nlminb's own convergence code should have been overridden by the polish's
  # own gradient-based criterion, with an honest message pointing at it.
  expect_identical(fit$opt$convergence, 0L)
  expect_match(fit$opt$message, "Newton polish")

  # Self-consistency gate: tightening further (a much stricter grad_tol/
  # max_iter on top of the already-polished optimum) moves the estimates by
  # less than 1e-7 -- the reported optimum is not an artifact of the default
  # polish's own stopping tolerance.
  tighter <- drmTMB:::drm_newton_polish(
    fit$opt,
    fit$obj$fn,
    fit$obj$gr,
    grad_tol = 1e-12,
    max_iter = 5L
  )
  expect_lt(max(abs(tighter$par - fit$opt$par)), 1e-7)
})

test_that("newton_polish = FALSE restores the raw nlminb optimum (#1130)", {
  dat <- s10_varying_scale_fixture()
  fit_polished <- drmTMB(bf(y ~ x + (1 | g), sigma ~ x), data = dat, engine = "tmb")
  fit_raw <- drmTMB(
    bf(y ~ x + (1 | g), sigma ~ x),
    data = dat,
    engine = "tmb",
    control = drm_control(newton_polish = FALSE)
  )

  # The raw fit reports nlminb's own convergence code/message untouched.
  expect_identical(fit_raw$opt$convergence, 0L)
  expect_false(grepl("Newton polish", fit_raw$opt$message, fixed = TRUE))

  # The two optima differ by the same order of magnitude as the #1130 shortfall.
  expect_gt(max(abs(fit_raw$opt$par - fit_polished$opt$par)), 1e-6)
})

# CI follow-up (2026-09-03): the Newton polish above ran on the free
# (unconstrained) fit only. `confint(..., method = "profile", profile_engine
# = "endpoint")` compares that free optimum's nll against a CONSTRAINED
# endpoint solve (`profile_endpoint_evaluator()`, `R/profile.R`), which was
# left unpolished -- comparing a polished nll against an unpolished one biases
# the profile, since the unpolished (constrained) side stops short of its true
# minimum and so reports a higher nll than it should. On the bivariate
# lognormal penguin vignette (`vignettes/bivariate-nongaussian.Rmd`, chunk
# `penguin-intervals`) this pushed the endpoint solve's reported gradient
# (0.002724) past `PROFILE_ENDPOINT_GRADIENT_TOL` (1e-3), so the interval came
# back `profile_failed` with NA bounds and the vignette's `plot.window()` call
# errored ("need finite 'xlim' values"). The fix applies the same polish to
# the constrained endpoint solve (`solve_from()`, same file), gated on
# `object$control$newton_polish` so `drm_control(newton_polish = FALSE)`
# leaves both sides unpolished and the comparison symmetric either way.
test_that("profile endpoint polish keeps the rho12 interval finite and not narrowed (#1130 CI)", {
  testthat::skip_if_not_installed("palmerpenguins")

  penguins <- subset(
    palmerpenguins::penguins,
    stats::complete.cases(species, sex, year, flipper_length_mm, body_mass_g) &
      flipper_length_mm > 0 & body_mass_g > 0
  )
  penguins$year_c <- penguins$year - mean(penguins$year)

  form <- bf(
    mu1 = flipper_length_mm ~ species + sex + year_c,
    mu2 = body_mass_g ~ species + sex + year_c,
    sigma1 = ~1, sigma2 = ~1, rho12 = ~1
  )

  fit_polished <- drmTMB(form, family = biv_lognormal(), data = penguins)
  ci_polished <- confint(
    fit_polished,
    parm = "rho12",
    method = "profile",
    profile_engine = "endpoint"
  )

  expect_true(is.finite(ci_polished$lower))
  expect_true(is.finite(ci_polished$upper))
  expect_identical(ci_polished$conf.status, "profile")

  # Baseline: both sides unpolished (symmetric by construction), so this is
  # not the pre-fix asymmetric bug -- it is the reference width a future
  # regression that re-narrows the polished interval must be caught against.
  fit_unpolished <- drmTMB(
    form,
    family = biv_lognormal(),
    data = penguins,
    control = drm_control(newton_polish = FALSE)
  )
  ci_unpolished <- confint(
    fit_unpolished,
    parm = "rho12",
    method = "profile",
    profile_engine = "endpoint"
  )

  width_polished <- ci_polished$upper - ci_polished$lower
  width_unpolished <- ci_unpolished$upper - ci_unpolished$lower
  expect_gt(width_polished, width_unpolished - 1e-4)
})
