# The parity matrix (docs/design/parity-matrix.md, generated by
# tools/write-parity-matrix.R) joins the family REGISTRY to the bridge ledger
# TSV. Three things are pinned here (parity-joint A2, 2026-09-05):
#
#  (a) every route the bridge ADMITS has a TSV row. A3 already ledgered the
#      routes admitted before A4; A4 registers five more families
#      (truncated_nbinom2, zero_one_beta, tweedie, cumulative_logit,
#      beta_binomial) one row per PR, and each one's TSV row lands separately
#      (PR #1184, branch claude/parity-a4-integration). Until #1184 merges,
#      this test SKIPS on exactly the known-pending set named below rather
#      than failing red; it is still the live red control for any OTHER
#      newly-admitted `fe` family that lands here without a TSV row.
#  (b) the `phylo_gamma_beta_binomial` naming trap: a reader that matches
#      capability_id substrings reports beta_binomial as covered from that
#      row alone, even though its syntax never calls beta_binomial(). The
#      matcher joins on the `syntax` column instead. (beta_binomial itself
#      was admitted for real by #1172, already in this branch's history --
#      it has its own genuine `fe_beta_binomial` row, so the trap is tested
#      against the trap row in isolation, not against the whole table.)
#  (c) regeneration is idempotent, and the committed artefact is current when
#      the DRM.jl clone at hand is at the pin the artefact names.
#
# The matcher below is a TWIN of the one in tools/write-parity-matrix.R --
# tools/ is .Rbuildignore'd, so the installed package cannot source it. The
# last test asserts the twins agree whenever the tool file is reachable.

pm_test_family_constructor <- function(family) {
  if (identical(family, "gamma")) {
    "Gamma"
  } else if (identical(family, "beta")) {
    "beta_family"
  } else {
    family
  }
}

pm_test_modifier_dpars <- function() c("zi", "hu", "zoi", "coi")

# Twin of tools/write-parity-matrix.R's pm_intrinsic_modifier_dpars(): which
# modifier dpars are INTRINSIC to `family` (zero_one_beta's zoi/coi), derived
# from the family's own `drm_family` object, never hard-coded per family.
pm_test_intrinsic_modifier_dpars <- function(family) {
  obj <- drmTMB:::drm_julia_registry_family_object(family)
  if (is.null(obj) || is.null(obj$dpars)) {
    return(character())
  }
  intersect(pm_test_modifier_dpars(), obj$dpars)
}

pm_test_syntax_calls <- function(syntax, constructor) {
  grepl(paste0("(^|[^A-Za-z0-9_.])", constructor, "\\("), syntax, perl = TRUE)
}

pm_test_syntax_has_modifier <- function(syntax, dpar) {
  grepl(paste0("(^|[^A-Za-z0-9_.])", dpar, "\\s*(=\\s*)?~"), syntax, perl = TRUE)
}

pm_test_tsv_rows_for_family <- function(tsv, family, modifier = NULL) {
  hit <- tsv$route == "base" & pm_test_syntax_calls(tsv$syntax, pm_test_family_constructor(family))
  extraneous_mods <- setdiff(pm_test_modifier_dpars(), pm_test_intrinsic_modifier_dpars(family))
  any_mod <- if (length(extraneous_mods)) {
    Reduce(`|`, lapply(extraneous_mods, function(d) pm_test_syntax_has_modifier(tsv$syntax, d)))
  } else {
    rep(FALSE, nrow(tsv))
  }
  has_re_term <- grepl("|", tsv$syntax, fixed = TRUE)
  if (is.null(modifier)) hit & !any_mod & !has_re_term else hit & pm_test_syntax_has_modifier(tsv$syntax, modifier)
}

# Native modifier model types as the BRIDGE spells them (hurdle NB2 reaches
# DRM.jl as nbinom2() + `hu ~`; native drmTMB spells it truncated_nbinom2()).
pm_test_modifier_routes <- function() {
  data.frame(
    model_type = c("zi_poisson", "zi_nbinom2", "hurdle_nbinom2"),
    native_family = c("poisson", "nbinom2", "truncated_nbinom2"),
    bridge_family = c("poisson", "nbinom2", "nbinom2"),
    modifier = c("zi", "zi", "hu"),
    stringsAsFactors = FALSE
  )
}

pm_test_admitted_routes <- function(registry, supported_dpars) {
  fe <- vapply(registry[vapply(registry, function(s) isTRUE(s$fe), logical(1L))], `[[`, character(1L), "family")
  routes <- data.frame(route = fe, family = fe, modifier = NA_character_, stringsAsFactors = FALSE)
  mods <- pm_test_modifier_routes()
  keep <- mods$bridge_family %in% fe & mods$modifier %in% supported_dpars
  if (any(keep)) {
    m <- mods[keep, , drop = FALSE]
    routes <- rbind(routes, data.frame(
      route = paste0(m$bridge_family, "+", m$modifier),
      family = m$bridge_family, modifier = m$modifier, stringsAsFactors = FALSE
    ))
  }
  rownames(routes) <- NULL
  routes
}

pm_test_routes_without_row <- function(routes, tsv) {
  covered <- vapply(seq_len(nrow(routes)), function(i) {
    mod <- if (is.na(routes$modifier[[i]])) NULL else routes$modifier[[i]]
    any(pm_test_tsv_rows_for_family(tsv, routes$family[[i]], mod))
  }, logical(1L))
  routes$route[!covered]
}

pm_test_read_tsv <- function() {
  path <- system.file("extdata", "julia-capabilities.tsv", package = "drmTMB")
  expect_true(nzchar(path))
  tab <- utils::read.delim(path, stringsAsFactors = FALSE, check.names = FALSE, quote = "", encoding = "UTF-8")
  tab[] <- lapply(tab, as.character)
  tab
}

pm_test_tool_path <- function() {
  # Only reachable from a source checkout (tools/ is .Rbuildignore'd).
  path <- testthat::test_path("..", "..", "tools", "write-parity-matrix.R")
  if (file.exists(path)) normalizePath(path) else ""
}

pm_test_source_tool <- function(path) {
  env <- new.env(parent = globalenv())
  sys.source(path, envir = env)
  env
}

test_that("every route the bridge admits has a TSV row", {
  tsv <- pm_test_read_tsv()
  routes <- pm_test_admitted_routes(
    drmTMB:::drm_julia_family_registry(),
    drmTMB:::julia_bridge_supported_dpars()
  )
  # The enumeration is grounded in the bridge, not in this file: every route's
  # family is admitted by drm_julia_family_tag() and its modifier is marshalled.
  for (i in seq_len(nrow(routes))) {
    expect_identical(drmTMB:::drm_julia_family_tag(routes$family[[i]]), routes$family[[i]])
  }
  expect_true(all(is.na(routes$modifier) | routes$modifier %in% drmTMB:::julia_bridge_supported_dpars()))
  expect_gte(nrow(routes), 9L)

  missing <- pm_test_routes_without_row(routes, tsv)

  # S1a (2026-09-24): #1184 merged 2026-09-06, so every A4 family's TSV row
  # has long since landed, and the S1a join fix (tools/write-parity-matrix.R's
  # pm_intrinsic_modifier_dpars()) lets `fe_zero_one_beta` join on the plain
  # family route too (zoi/coi are INTRINSIC to zero_one_beta, not a modifier
  # route). Measured empty at this pin. If a route the bridge admits is ever
  # KNOWINGLY left unledgered pending a later slice (Arc 1 plan S5's admission
  # census), name it here with a one-line reason -- never bring back a silent
  # skip.
  expected_unledgered_for_S5 <- character(0)

  new_gaps <- setdiff(missing, expected_unledgered_for_S5)
  fixed_early <- setdiff(expected_unledgered_for_S5, missing)
  expect(
    length(new_gaps) == 0L && length(fixed_early) == 0L,
    sprintf(
      paste0(
        "the bridge-admitted routes and expected_unledgered_for_S5 have drifted apart (route == \"base\" ",
        "and syntax calling the family constructor%s): NEW GAPS not in expected_unledgered_for_S5: %s; ",
        "entries in expected_unledgered_for_S5 that are no longer missing (update the S5 note): %s"
      ),
      " plus the modifier's `dpar ~` formula for a modifier route",
      if (length(new_gaps)) paste(new_gaps, collapse = ", ") else "(none)",
      if (length(fixed_early)) paste(fixed_early, collapse = ", ") else "(none)"
    )
  )
})

test_that("beta_binomial is NOT reported covered by the phylo_gamma_beta_binomial row", {
  tsv <- pm_test_read_tsv()
  trap <- tsv[tsv$capability_id == "phylo_gamma_beta_binomial", , drop = FALSE]
  expect_identical(nrow(trap), 1L)

  # POSITIVE CONTROL: the trap is real -- a capability_id substring reader
  # says beta_binomial has a row.
  expect_true(any(grepl("beta_binomial", tsv$capability_id, fixed = TRUE)))

  # The syntax join does not: the row's syntax calls Gamma(), beta_family() and
  # stats::binomial(), never beta_binomial().
  expect_true(pm_test_syntax_calls(trap$syntax, "Gamma"))
  expect_true(pm_test_syntax_calls(trap$syntax, "beta_family"))
  expect_true(pm_test_syntax_calls(trap$syntax, "binomial"))
  expect_false(pm_test_syntax_calls(trap$syntax, "beta_binomial"))
  # Tested against the trap row IN ISOLATION: beta_binomial is genuinely
  # admitted elsewhere in this table (fe_beta_binomial, #1172), so asserting
  # this against the whole `tsv` would conflate "the trap alone does not
  # fool the matcher" with "beta_binomial has no row at all" -- the second
  # claim is false and is asserted the other way below.
  expect_false(any(pm_test_tsv_rows_for_family(trap, "beta_binomial")))

  # And the converse: a beta_binomial() call evidences neither beta nor binomial.
  bb <- "bf(y ~ x, sigma ~ 1), family = beta_binomial(), engine = \"julia\""
  expect_true(pm_test_syntax_calls(bb, "beta_binomial"))
  expect_false(pm_test_syntax_calls(bb, "beta"))
  expect_false(pm_test_syntax_calls(bb, "binomial"))

  # A ZIP row evidences the zi route, not plain Poisson.
  zip <- data.frame(route = "base", syntax = "bf(y ~ x, zi ~ x), family = poisson(), engine = \"julia\"", stringsAsFactors = FALSE)
  expect_true(pm_test_tsv_rows_for_family(zip, "poisson", "zi"))
  expect_false(pm_test_tsv_rows_for_family(zip, "poisson"))

  # The bridge refused beta_binomial when this test was first written; #1172
  # (already in this branch's history) admitted it for real, with a registry
  # row (spec("beta_binomial", fe = TRUE)) AND a TSV row whose syntax calls
  # beta_binomial() -- so the tag now returns the family unchanged instead of
  # erroring, and the whole-table match legitimately reports it covered.
  expect_identical(drmTMB:::drm_julia_family_tag("beta_binomial"), "beta_binomial")
  expect_true(any(pm_test_tsv_rows_for_family(tsv, "beta_binomial")))
})

test_that("an ordinary random-effect TSV row is not absorbed by the plain fixed-effect family match", {
  # RED CONTROL for this guard: without the `|` exclusion, `gaussian` with no
  # modifier matches base_gaussian_location_scale AND the three ordinary-RE
  # rows A5 ledgered (route == "base", syntax calls gaussian(), no zi/hu/zoi/coi
  # formula -- but a `(1 | g)` term instead). The plain family route must match
  # exactly the one fixed-effect-only row.
  tsv <- pm_test_read_tsv()
  hit <- pm_test_tsv_rows_for_family(tsv, "gaussian")
  expect_identical(tsv$capability_id[hit], "base_gaussian_location_scale")
  re_ids <- c("gaussian_random_intercept_mu", "gaussian_random_slope_mu", "gaussian_sigma_random_intercept")
  expect_true(all(re_ids %in% tsv$capability_id))
  expect_false(any(tsv$capability_id[hit] %in% re_ids))
})

test_that("tools/write-parity-matrix.R regenerates byte-identically and matches the committed artefact at its pin", {
  tool <- pm_test_tool_path()
  skip_if(!nzchar(tool), "tools/write-parity-matrix.R is not reachable (installed package)")
  drmjl <- Sys.getenv("DRM_JL_PATH", unset = "")
  skip_if(!nzchar(drmjl) || !dir.exists(drmjl), "DRM_JL_PATH is not set to a DRM.jl clone")
  root <- normalizePath(testthat::test_path("..", ".."))

  env <- pm_test_source_tool(tool)
  out1 <- tempfile(fileext = ".md")
  out2 <- tempfile(fileext = ".md")
  suppressMessages(env$pm_write_matrix(root, drmjl, out1))
  suppressMessages(env$pm_write_matrix(root, drmjl, out2))
  expect_identical(readLines(out1, warn = FALSE), readLines(out2, warn = FALSE))

  gen <- readLines(out1, warn = FALSE)
  expect_true(any(grepl("^## The matrix$", gen)))
  n_rows <- sum(grepl("^\\| (GREEN )?`", gen))
  expect_identical(n_rows, nrow(env$pm_parse_status_table(readLines(file.path(root, "docs", "design", "capability-status.md"), warn = FALSE))))

  committed_path <- file.path(root, "docs", "design", "parity-matrix.md")
  expect_true(file.exists(committed_path))
  committed <- readLines(committed_path, warn = FALSE)
  pin_line <- grep("at pin `[0-9a-f]{40}`", committed, value = TRUE)
  expect_length(pin_line, 1L)
  committed_pin <- sub(".*at pin `([0-9a-f]{40})`.*", "\\1", pin_line)
  clone_pin <- env$pm_git(drmjl, "rev-parse", "HEAD")
  if (identical(clone_pin, committed_pin)) {
    expect_identical(gen, committed)
  } else {
    skip(sprintf("DRM.jl clone is at %s, committed artefact was generated at %s: currency not checked", substr(clone_pin, 1, 8), substr(committed_pin, 1, 8)))
  }
})

test_that("the test's matcher twin agrees with the tool's matcher", {
  tool <- pm_test_tool_path()
  skip_if(!nzchar(tool), "tools/write-parity-matrix.R is not reachable (installed package)")
  env <- pm_test_source_tool(tool)
  tsv <- pm_test_read_tsv()
  registry <- drmTMB:::drm_julia_family_registry()
  dpars <- drmTMB:::julia_bridge_supported_dpars()
  expect_identical(env$pm_modifier_routes(), pm_test_modifier_routes())
  expect_identical(env$pm_admitted_routes(registry, dpars), pm_test_admitted_routes(registry, dpars))
  routes <- pm_test_admitted_routes(registry, dpars)
  expect_identical(env$pm_routes_without_row(routes, tsv), pm_test_routes_without_row(routes, tsv))
  fams <- c(vapply(registry, `[[`, character(1L), "family"), "beta_binomial", "tweedie", "truncated_nbinom2")
  for (f in fams) {
    expect_identical(env$pm_tsv_rows_for_family(tsv, f), pm_test_tsv_rows_for_family(tsv, f), info = f)
    for (m in pm_test_modifier_dpars()) {
      expect_identical(env$pm_tsv_rows_for_family(tsv, f, m), pm_test_tsv_rows_for_family(tsv, f, m), info = paste(f, m))
    }
  }
})

# Why this test exists (2026-09-07). `pm_grep_line()` aborts when a citation
# anchor is missing -- it fails CLOSED, which is right. But the only test that
# exercised the generator end-to-end skips without `DRM_JL_PATH`, so CI never
# runs it, and #1187 landed a rewrite of
#   fixef_profile_ready <- !is_biv && !is.null(object$bridge_payload)
# into
#   fixef_profile_ready <- !is.null(payload) && !is_biv_structured
# leaving `tools/write-parity-matrix.R` broken on main with nothing red. This
# test resolves every anchor with NO DRM.jl clone, so it runs in CI, where the
# breakage would have surfaced on #1187's own PR.
test_that("every citation anchor in write-parity-matrix.R still resolves in its source file", {
  tool <- pm_test_tool_path()
  skip_if(!nzchar(tool), "tools/write-parity-matrix.R is not reachable (installed package)")
  root <- normalizePath(testthat::test_path("..", ".."))
  src <- readLines(tool, warn = FALSE)

  # The file-key -> path map, read from the tool rather than duplicated here, so
  # a renamed source file cannot make this test pass by disagreeing with it.
  key_paths <- c(
    r_status = "docs/design/capability-status.md",
    registry = "R/julia-family-registry.R",
    bridge = "R/julia-bridge.R",
    drmtmb = "R/drmTMB.R",
    heritability = "R/heritability.R",
    plan = "docs/dev-log/loop/parity-joint-20260905/ultra-plan.md"
  )
  for (k in names(key_paths)) {
    expect_true(
      any(grepl(sprintf('%s = "%s"', k, key_paths[[k]]), src, fixed = TRUE)),
      info = sprintf("file-key '%s' no longer maps to %s in the tool", k, key_paths[[k]])
    )
  }

  # Every `r("<key>", "<literal>")` call. The literal may contain escaped quotes.
  calls <- regmatches(src, gregexpr('\\br\\("[a-z_]+", "(\\\\.|[^"\\\\])*"', src))
  calls <- unlist(calls, use.names = FALSE)
  expect_gt(length(calls), 15L)   # a regex that silently matched nothing would pass vacuously

  keys <- sub('^\\br\\("([a-z_]+)".*$', "\\1", calls)
  lits <- sub('^\\br\\("[a-z_]+", "(.*)"$', "\\1", calls)
  # Undo the R source-level escaping by letting the R parser do it rather than by
  # hand: a hand-rolled gsub pair got the backslash-quote case wrong on the first
  # run and reported two anchors missing that were in fact present -- exactly the
  # false alarm this test exists to avoid producing.
  lits <- vapply(lits, function(x) eval(parse(text = paste0('"', x, '"'))), character(1), USE.NAMES = FALSE)

  cache <- list()
  missing <- character()
  for (i in seq_along(calls)) {
    k <- keys[[i]]
    expect_true(k %in% names(key_paths), info = sprintf("unknown file key '%s'", k))
    if (is.null(cache[[k]])) {
      cache[[k]] <- readLines(file.path(root, key_paths[[k]]), warn = FALSE)
    }
    if (!any(grepl(lits[[i]], cache[[k]], fixed = TRUE))) {
      missing <- c(missing, sprintf("%s: %s", key_paths[[k]], lits[[i]]))
    }
  }
  expect_identical(
    missing, character(),
    info = paste0("citation anchors that no longer resolve:\n  ", paste(missing, collapse = "\n  "))
  )

  # RED CONTROL: a checker that can only ever say "fine" is worthless. An anchor
  # that is genuinely absent must be reported absent.
  expect_false(any(grepl("fixef_profile_ready <- !is_biv && !is.null(object$bridge_payload)",
                         cache[["bridge"]], fixed = TRUE)))
})
