test_that("AOI-3 private full-refit runner keeps its frozen execution boundary", {
  runner <- test_path("..", "..", "tools", "run-aoi3-bernoulli-nb2-full-refit.R")
  reducer <- test_path("..", "..", "tools", "summarize-aoi3-bernoulli-nb2-smoke.R")
  contract <- test_path("..", "..", "docs", "dev-log", "2026-07-31-aoi3-full-refit-calibration-contract.md")
  expect_silent(parse(file = runner))
  expect_silent(parse(file = reducer))
  text <- paste(readLines(runner, warn = FALSE), collapse = "\n")
  expect_match(text, "drm_pair_general_eta_sandwich", fixed = TRUE)
  expect_match(text, "simulate_inner", fixed = TRUE)
  expect_match(text, "fit_complete", fixed = TRUE)
  expect_match(text, "outer-sandwich-covariance.csv", fixed = TRUE)
  contract_text <- paste(readLines(contract, warn = FALSE), collapse = "\n")
  expect_match(contract_text, "1,194,000", fixed = TRUE)
  expect_match(contract_text, "non-covering", fixed = TRUE)
  expect_match(contract_text, "AOI-2 point-recovery HOLD", fixed = TRUE)
})
