#!/usr/bin/env bash
# Fail closed unless a staged source archive is either exactly `git archive`
# output, or a declared source subset whose every file is the declared
# commit's blob.  The latter is the retained campaign's portable source
# staging contract.
set -euo pipefail

if [[ $# -ne 4 && $# -ne 5 && $# -ne 6 ]]; then
  printf '%s\n' 'usage: verify-source-commit <label> <40-hex-commit> <source.bundle> <source.tar.gz> [required-root,...] [archive-prefix/]' >&2
  exit 64
fi

readonly label=$1
readonly commit=$2
readonly bundle=$3
readonly archive=$4
readonly required_roots="${5:-}"
readonly archive_prefix="${6:-}"

if [[ ! "${label}" =~ ^[A-Za-z0-9_-]+$ ]]; then
  printf '%s\n' 'source-proof label must contain only letters, digits, underscore, or hyphen' >&2
  exit 64
fi
if [[ ! "${commit}" =~ ^[0-9a-fA-F]{40}$ ]]; then
  printf '%s\n' 'source-proof commit must be a full 40-hex object ID' >&2
  exit 64
fi
if [[ ! -f "${bundle}" || ! -f "${archive}" ]]; then
  printf '%s\n' 'source-proof requires an existing bundle and gzip archive' >&2
  exit 66
fi

if [[ -n "${required_roots}" ]] && [[ ! "${required_roots}" =~ ^[A-Za-z0-9._/-]+(,[A-Za-z0-9._/-]+)*$ ]]; then
  printf '%s\n' 'source-proof required roots must be a comma-separated relative path list' >&2
  exit 64
fi
if [[ -n "${archive_prefix}" ]] && [[ ! "${archive_prefix}" =~ ^[A-Za-z0-9_.-]+/$ ]]; then
  printf '%s\n' 'source-proof archive prefix must be empty or one safe directory ending in slash' >&2
  exit 64
fi
if [[ -n "${archive_prefix}" && -z "${required_roots}" ]]; then
  printf '%s\n' 'source-proof archive prefix requires a source-subset proof' >&2
  exit 64
fi

readonly tmp="$(mktemp -d "${TMPDIR:-/tmp}/071-source-proof.XXXXXX")"
trap 'rm -rf "${tmp}"' EXIT

sha256_stream() {
  if command -v sha256sum > /dev/null 2>&1; then
    sha256sum | awk '{print $1}'
  else
    shasum -a 256 | awk '{print $1}'
  fi
}

# Reject absolute and parent-traversal members before extraction. Campaign
# archives are generated by `git archive`, so any such member is corruption.
if tar -tzf "${archive}" | awk '
  /^\// || /^\.\.($|\/)/ || /\/\.\.($|\/)/ { bad = 1 }
  END { exit bad ? 0 : 1 }
'; then
  printf '%s\n' 'source-proof archive contains an unsafe path' >&2
  exit 65
fi

git clone --quiet --no-checkout "${bundle}" "${tmp}/repo"
git -C "${tmp}/repo" bundle verify "${bundle}" > "${tmp}/bundle-verify.txt"
git -C "${tmp}/repo" cat-file -e "${commit}^{tree}"

if [[ -z "${required_roots}" ]]; then
  expected_tar_sha256="$(git -C "${tmp}/repo" archive --format=tar "${commit}" | sha256_stream)"
  observed_tar_sha256="$(gzip -dc "${archive}" | sha256_stream)"
  if [[ "${expected_tar_sha256}" != "${observed_tar_sha256}" ]]; then
    printf '%s\n' 'source-proof archive does not equal git archive of the declared commit' >&2
    exit 65
  fi
  printf 'SOURCE_COMMIT_PROOF_PASS label=%s commit=%s\n' "${label}" "${commit}"
  exit 0
fi

readonly staging_root="${tmp}/staged"
mkdir -p "${staging_root}"
tar -xzf "${archive}" -C "${staging_root}"
staged="${staging_root}"

# The retained drmTMB payload is wrapped in one portable top-level directory.
# It is structural packaging, not part of the source paths to prove.
if [[ -n "${archive_prefix}" ]]; then
  wrapper="${staging_root}/${archive_prefix%/}"
  if [[ -d "${wrapper}" ]]; then
    if find "${staging_root}" -mindepth 1 -maxdepth 1 -not -name "${archive_prefix%/}" -print -quit | grep -q .; then
      printf '%s\n' 'source-proof subset has entries outside its declared archive prefix' >&2
      exit 65
    fi
    staged="${wrapper}"
  else
    # GNU tar on the retained Nibi archive exposes the same source payload
    # without its harmless wrapper component.  Both forms prove the identical
    # logical root; an unexpected wrapper is never accepted as a source path.
    staged="${staging_root}"
  fi
fi

# A source subset is a materialized, ordinary file tree.  Links and special
# files would make the byte-to-blob proof ambiguous, so reject them.
if find "${staged}" \( -type l -o -type b -o -type c -o -type p -o -type s \) -print -quit | grep -q .; then
  printf '%s\n' 'source-proof subset archive contains a link or special file' >&2
  exit 65
fi

IFS=',' read -r -a roots <<< "${required_roots}"
for root in "${roots[@]}"; do
  if [[ "${root}" == .* || "${root}" == */.. || "${root}" == ../* || "${root}" == /* ]]; then
    printf '%s\n' 'source-proof required root is unsafe' >&2
    exit 64
  fi
  if [[ ! -e "${staged}/${root}" ]]; then
    printf 'source-proof subset is missing required root: %s\n' "${root}" >&2
    exit 65
  fi
done

# Every staged file must be present at the pinned commit with the same bytes.
# Empty extra directories are rejected too, so the archive represents only a
# subset of the declared source tree, never an arbitrary filesystem tree.
while IFS= read -r -d '' path; do
  rel="${path#${staged}/}"
  if [[ "${rel}" == "${path}" ]]; then
    continue
  fi
  if [[ -d "${path}" ]]; then
    [[ "$(git -C "${tmp}/repo" cat-file -t "${commit}:${rel}" 2>/dev/null || true)" == tree ]] || {
      printf 'source-proof subset contains directory absent from commit: %s\n' "${rel}" >&2
      exit 65
    }
  elif [[ -f "${path}" ]]; then
    git -C "${tmp}/repo" cat-file -e "${commit}:${rel}" || {
      printf 'source-proof subset contains file absent from commit: %s\n' "${rel}" >&2
      exit 65
    }
    if ! git -C "${tmp}/repo" show "${commit}:${rel}" | cmp -s - "${path}"; then
      printf 'source-proof subset file differs from commit blob: %s\n' "${rel}" >&2
      exit 65
    fi
  else
    printf 'source-proof subset contains unsupported entry: %s\n' "${rel}" >&2
    exit 65
  fi
done < <(find "${staged}" -mindepth 1 -print0)

printf 'SOURCE_COMMIT_SUBSET_PROOF_PASS label=%s commit=%s\n' "${label}" "${commit}"
