#!/usr/bin/env bash
# Fail closed unless a staged source archive is exactly `git archive` output
# from the declared commit contained in its staged Git bundle.
set -euo pipefail

if [[ $# -ne 4 ]]; then
  printf '%s\n' 'usage: verify-source-commit <label> <40-hex-commit> <source.bundle> <source.tar.gz>' >&2
  exit 64
fi

readonly label=$1
readonly commit=$2
readonly bundle=$3
readonly archive=$4

if [[ ! "${label}" =~ ^[A-Za-z0-9_-]+$ ]]; then
  printf '%s\n' 'source-proof label must contain only letters, digits, underscore, or hyphen' >&2
  exit 64
fi
if [[ ! "${commit}" =~ ^[0-9a-fA-F]{40}$ ]]; then
  printf '%s\n' 'source-proof commit must be a full 40-hex object ID' >&2
  exit 64
fi
if [[ ! -f "${bundle}" || ! -f "${archive}" ]]; then
  printf '%s\n' 'source-proof requires an existing bundle and gzip archive' >&2
  exit 66
fi

readonly tmp="$(mktemp -d "${TMPDIR:-/tmp}/071-source-proof.XXXXXX")"
trap 'rm -rf "${tmp}"' EXIT

# Reject absolute and parent-traversal members before extraction. Campaign
# archives are generated by `git archive`, so any such member is corruption.
if tar -tzf "${archive}" | awk '
  /^\// || /^\.\.($|\/)/ || /\/\.\.($|\/)/ { bad = 1 }
  END { exit bad ? 0 : 1 }
'; then
  printf '%s\n' 'source-proof archive contains an unsafe path' >&2
  exit 65
fi

git clone --quiet --no-checkout "${bundle}" "${tmp}/repo"
git -C "${tmp}/repo" bundle verify "${bundle}" > "${tmp}/bundle-verify.txt"
git -C "${tmp}/repo" cat-file -e "${commit}^{tree}"

mkdir "${tmp}/expected" "${tmp}/observed"
git -C "${tmp}/repo" archive --format=tar "${commit}" | tar -xf - -C "${tmp}/expected"
tar -xzf "${archive}" -C "${tmp}/observed"
diff -qr "${tmp}/expected" "${tmp}/observed" > "${tmp}/tree-diff.txt"

printf 'SOURCE_COMMIT_PROOF_PASS label=%s commit=%s\n' "${label}" "${commit}"
