#!/usr/bin/env Rscript
# Promote exactly the three retained scalar-q1 receipts, never a provider-wide route.
scalar_promote_stop <- function(...) stop(..., call.=FALSE)
scalar_promote_hash <- function(path) { cmd<-if(nzchar(Sys.which("sha256sum")))"sha256sum"else"shasum";out<-system2(cmd,if(identical(cmd,"sha256sum"))path else c("-a","256",path),stdout=TRUE,stderr=TRUE);if(!length(out)||!grepl("^[0-9a-f]{64}\\s",out[[1L]]))scalar_promote_stop("Cannot hash ",path);sub("\\s.*$","",out[[1L]]) }
scalar_promote_main <- function(args=commandArgs(trailingOnly=TRUE)) {
  keyed<-args[grepl("^--[A-Za-z][A-Za-z-]*=",args)];v<-sub("^[^=]+=","",keyed);names(v)<-sub("^--([^=]+)=.*$","\\1",keyed);if(!"--write"%in%args||!setequal(names(v),c("ledger-dir","date","goal-authorized"))||!identical(v[["goal-authorized"]],"lane-b-144-goal"))scalar_promote_stop("Requires --write, --ledger-dir, --date, and --goal-authorized=lane-b-144-goal.")
  root<-normalizePath(".",mustWork=TRUE); control<-utils::read.delim(file.path(root,"docs/dev-log/evidence/2026-07-28-lane-b-k12-dense-lss-direct-sd-control.tsv"),check.names=FALSE,stringsAsFactors=FALSE);if(nrow(control)!=2L||any(control$interval_status!="incomplete")||any(control$usable_and_covering!=0L))scalar_promote_stop("K12 control is not fail-closed.")
  source(file.path(root,"tools/validate-lane-b-scalar-animal-relmat-q1-highinfo-contracts.R"),local=TRUE);contracts<-lane_b_scalar_q1_read_validate(root);sha<-paste(system2("git",c("-C",root,"rev-parse","HEAD"),stdout=TRUE),collapse="")
  # Evidence was executed on 48a16f before this promoter was added; retain that exact source SHA.
  if(!identical(sha,"48a16f5180907bc7c8b3e060537fcf09b4c97d1f")) scalar_promote_stop("Unexpected evidence source SHA.")
  receipts<-lapply(contracts$cell_id,function(cell){p<-file.path(root,"docs/dev-log/interval-feasibility/results",sha,"scalar-animal-relmat-q1-highinfo",cell);f<-list.files(p,pattern="receipt\\.tsv$",full.names=TRUE);if(length(f)!=1L)scalar_promote_stop("Missing unique receipt for ",cell);utils::read.delim(f,check.names=FALSE,stringsAsFactors=FALSE)})
  for(i in seq_along(receipts)){x<-receipts[[i]];pass<-nrow(x)==1L&&identical(x$cell_id[[1L]],contracts$cell_id[[i]])&&identical(x$target_id[[1L]],contracts$target_id[[i]])&&identical(x$dgp_id[[1L]],contracts$dgp_id[[i]])&&identical(x$source_sha[[1L]],sha)&&identical(x$conf_status[[1L]],"profile")&&identical(x$profile_engine[[1L]],"tmbprofile")&&isTRUE(x$trace_complete[[1L]])&&!isTRUE(x$profile_boundary[[1L]])&&!isTRUE(x$clamp_limited[[1L]])&&x$convergence[[1L]]==0L&&isTRUE(x$pdHess[[1L]])&&all(is.finite(unlist(x[c("estimate","lower","upper")])))&&x$lower[[1L]]<x$upper[[1L]]&&x$estimate[[1L]]>=x$lower[[1L]]&&x$estimate[[1L]]<=x$upper[[1L]]&&(is.na(x$failure_reason[[1L]])||!nzchar(x$failure_reason[[1L]]))&&identical(scalar_promote_hash(x$trace_path[[1L]]),x$trace_sha256[[1L]])&&identical(scalar_promote_hash(x$interval_path[[1L]]),x$interval_sha256[[1L]]);if(!pass)scalar_promote_stop("Receipt fails exact gate: ",contracts$cell_id[[i]])}
  ledger<-v[["ledger-dir"]]; cells_path<-file.path(ledger,"cells.tsv"); evidence_path<-file.path(ledger,"evidence.tsv");transition_path<-file.path(ledger,"transitions.tsv");cells<-utils::read.delim(cells_path,check.names=FALSE,stringsAsFactors=FALSE);evidence<-utils::read.delim(evidence_path,check.names=FALSE,stringsAsFactors=FALSE);transition<-utils::read.delim(transition_path,check.names=FALSE,stringsAsFactors=FALSE)
  for(i in seq_len(nrow(contracts))){cell<-contracts$cell_id[[i]];j<-match(cell,cells$cell_id);ev<-paste0("ev-",cell,"-scalar-q1-highinfo-profile");tr<-paste0("tr-",cell,"-scalar-q1-highinfo-profile");if(is.na(j)||cells$evidence_tier[[j]]!="point_fit_recovery"||ev%in%evidence$evidence_id||tr%in%transition$transition_id)scalar_promote_stop("Ledger row not uniquely promotable: ",cell);boundary<-paste0("interval_feasible only for ",cell," x exact direct target ",contracts$profile_parameter[[i]]," x frozen n32 x 20 high-information Gaussian fixture with a retained complete unclamped tmbprofile receipt. No provider-wide, family-wide, coverage, calibration, inference-ready, public, or API claim follows.");cells$evidence_tier[[j]]<-"interval_feasible";cells$primary_evidence_id[[j]]<-ev;cells$claim_boundary[[j]]<-boundary;cells$next_gate[[j]]<-"Coverage/calibration require a separate pre-registered evidence arc.";cells$updated_commit[[j]]<-sha;cells$updated_date[[j]]<-v[["date"]];cells$notes[[j]]<-boundary
    add_ev<-data.frame(evidence_id=ev,cell_id=cell,evidence_class="contract_test",path_or_url=receipts[[i]]$trace_path[[1L]],commit_sha=sha,run_id="Lane B scalar animal/relmat q1 high-information profile batch",command="Rscript tools/promote-lane-b-scalar-animal-relmat-q1-highinfo-profile-receipts.R --write --goal-authorized=lane-b-144-goal",result="Retained complete unclamped tmbprofile with finite ordered endpoints, convergence 0, pdHess TRUE, and verified artifact hashes.",replicates="One fixed-seed n32 x 20 exact targetwise receipt.",reviewed_by="Codex Lane B mechanical gate",review_date=v[["date"]],claim_boundary=boundary,stringsAsFactors=FALSE);add_tr<-data.frame(transition_id=tr,cell_id=cell,from_work_status=cells$work_status[[j]],to_work_status=cells$work_status[[j]],evidence_ids=ev,reason="Approved Lane-B 144-goal exact scalar q1 profile receipt.",actor="Codex Lane B",commit_sha=sha,date=v[["date"]],stringsAsFactors=FALSE);utils::write.table(add_ev,evidence_path,sep="\t",row.names=FALSE,col.names=FALSE,quote=TRUE,append=TRUE);utils::write.table(add_tr,transition_path,sep="\t",row.names=FALSE,col.names=FALSE,quote=TRUE,append=TRUE)
  }
  raw<-readLines(cells_path,warn=FALSE);h<-strsplit(raw[[1L]],"\t",fixed=TRUE)[[1L]];changed<-c("evidence_tier","primary_evidence_id","claim_boundary","next_gate","updated_commit","updated_date","notes");for(cell in contracts$cell_id){line<-which(vapply(raw[-1L],function(z)strsplit(z,"\t",fixed=TRUE)[[1L]][[1L]]==cell,logical(1L)))+1L;j<-match(cell,cells$cell_id);f<-strsplit(raw[[line]],"\t",fixed=TRUE)[[1L]];f[match(changed,h)]<-as.character(cells[j,changed]);raw[[line]]<-paste(f,collapse="\t")};writeLines(raw,cells_path);message("Promoted three exact scalar q1 receipts.")
}
if(sys.nframe()==0L)scalar_promote_main()
