#!/usr/bin/env Rscript
# Exact targetwise q4 phylo location-SD receipt gate; scale components are withheld.
q4_stop <- function(...) stop(..., call. = FALSE)
q4_file <- grep("^--file=", commandArgs(FALSE), value = TRUE); q4_script <- normalizePath(if (length(q4_file)) sub("^--file=", "", q4_file[[1L]]) else "tools/run-lane-b-phylo-q4-location-profile-gate.R", mustWork = FALSE); q4_root <- normalizePath(file.path(dirname(q4_script), ".."), mustWork = TRUE)
q4_hash <- function(p) { cmd <- if (nzchar(Sys.which("sha256sum"))) "sha256sum" else "shasum"; z <- system2(cmd, if (identical(cmd, "sha256sum")) p else c("-a", "256", p), stdout = TRUE, stderr = TRUE); if (!length(z) || !grepl("^[0-9a-f]{64}\\s", z[[1L]])) q4_stop("Cannot hash ", p); sub("\\s.*$", "", z[[1L]]) }
q4_head <- function() paste(system2("git", c("-C", q4_root, "rev-parse", "HEAD"), stdout = TRUE), collapse = "")
q4_parse <- function(args) { if (identical(args, "--dry-run")) return(list(dry = TRUE)); v <- as.list(sub("^[^=]+=", "", args)); names(v) <- sub("^--([^=]+)=.*$", "\\1", args); req <- c("cell", "seed", "rung", "output-dir", "goal-authorized"); if (!setequal(names(v), req) || !identical(v[["goal-authorized"]], "lane-b-144-goal")) q4_stop("Requires exact --cell, --seed, --rung, --output-dir, and --goal-authorized=lane-b-144-goal."); list(dry = FALSE, v = v) }
q4_write <- function(x, p) { dir.create(dirname(p), recursive = TRUE, showWarnings = FALSE); utils::write.table(x, p, sep = "\t", quote = FALSE, row.names = FALSE, na = "") }
q4_main <- function(args = commandArgs(trailingOnly = TRUE)) {
  parsed <- q4_parse(args); ve <- new.env(parent = baseenv()); sys.source(file.path(q4_root, "tools", "validate-lane-b-phylo-q4-location-contracts.R"), envir = ve); registry <- ve$lane_b_phylo_q4_location_validate(q4_root)
  if (parsed$dry) { message("Validated q4 phylo high-rung contract: ", nrow(registry), " targets."); return(invisible(registry)) }
  v <- parsed$v; cell <- v$cell; seed <- as.integer(v$seed); rung <- v$rung; row <- registry[registry$cell_id == cell, , drop = FALSE]
  if (nrow(row) != 1L || !identical(seed, 3L) || !identical(rung, "high")) q4_stop("Only the exact high-rung q4 target is executable.")
  stem <- sprintf("lane-b-phylo-q4-location-profile-%s-high-seed-3", cell); paths <- list(trace = file.path(v[["output-dir"]], paste0(stem, "-trace.tsv")), interval = file.path(v[["output-dir"]], paste0(stem, "-interval.tsv")), receipt = file.path(v[["output-dir"]], paste0(stem, "-receipt.tsv"))); if (any(file.exists(unlist(paths)))) q4_stop("Refusing to replace retained artifact.")
  stage <- "adapter"
  tryCatch({
    ae <- new.env(parent = globalenv()); sys.source(file.path(q4_root, "tools", "lane-b-phylo-q4-location-adapters.R"), envir = ae); fixture <- ae$lane_b_phylo_q4_fixture(cell, seed, rung)
    if (!identical(fixture$truth$profile_parameter, row$profile_parameter[[1L]]) || !identical(fixture$truth$dgp_id, row$dgp_id[[1L]])) q4_stop("Adapter differs from frozen q4 contract.")
    stage <- "load"; pkgload::load_all(q4_root, quiet = TRUE, export_all = FALSE); stage <- "fit"; fit <- fixture$fit(fixture$data); target <- row$profile_parameter[[1L]]; targets <- drmTMB::profile_targets(fit)
    if (nrow(targets[targets$parm == target & targets$profile_ready %in% TRUE, , drop = FALSE]) != 1L) q4_stop("Q4 target is not uniquely profile-ready.")
    stage <- "profile"; prof <- stats::profile(fit, parm = target, trace = TRUE); trace <- as.data.frame(prof, stringsAsFactors = FALSE); if (!nrow(trace)) q4_stop("Empty profile trace.")
    one <- function(nm) { z <- unique(trace[[nm]]); if (length(z) != 1L) q4_stop("Trace has non-unique ", nm); z[[1L]] }; status <- as.character(one("conf.status")); msg <- as.character(one("profile.message")); lo <- as.numeric(one("conf.low")); hi <- as.numeric(one("conf.high")); est <- as.numeric(one("estimate")); di <- drmTMB:::profile_interval_diagnostics(c(lo, hi), transformation = as.character(one("transformation")), estimate = est); complete <- identical(status, "profile") && identical(msg, "ok")
    pass <- complete && !isTRUE(di$boundary) && !identical(status, "clamp_limited") && all(is.finite(c(est, lo, hi))) && lo < hi && est >= lo && est <= hi && fit$opt$convergence == 0L && isTRUE(fit$sdr$pdHess)
    trace$cell_id <- cell; trace$target_id <- row$target_id; trace$seed <- seed; trace$execution_information_rung <- rung; interval <- data.frame(cell_id = cell, target_id = row$target_id, dgp_id = row$dgp_id, seed = seed, lower = lo, upper = hi, profile_engine = "tmbprofile")
    q4_write(trace, paths$trace); q4_write(interval, paths$interval)
    receipt <- data.frame(cell_id = cell, target_id = row$target_id, dgp_id = row$dgp_id, dgp_version = row$dgp_version, formula = row$formula, true_parameter_scale = row$true_parameter_scale, profile_parameter = target, seed = seed, execution_information_rung = rung, source_sha = q4_head(), recorded_at = format(Sys.time(), tz = "UTC", usetz = TRUE), conf_status = if (pass) "profile" else "profile_failed", profile_engine = "tmbprofile", estimate = est, lower = if (pass) lo else NA_real_, upper = if (pass) hi else NA_real_, convergence = as.integer(fit$opt$convergence), pdHess = isTRUE(fit$sdr$pdHess), profile_boundary = isTRUE(di$boundary), clamp_limited = identical(status, "clamp_limited"), trace_complete = complete, failure_reason = if (pass) NA_character_ else if (isTRUE(di$boundary)) di$message else msg, promotion_eligible = FALSE, runner_sha256 = q4_hash(q4_script), adapter_sha256 = q4_hash(file.path(q4_root, "tools", "lane-b-phylo-q4-location-adapters.R")), trace_path = normalizePath(paths$trace, mustWork = TRUE), interval_path = normalizePath(paths$interval, mustWork = TRUE), trace_sha256 = q4_hash(paths$trace), interval_sha256 = q4_hash(paths$interval), stringsAsFactors = FALSE)
    q4_write(receipt, paths$receipt); message("Q4 phylo location receipt: ", cell, " / ", receipt$conf_status)
  }, error = function(e) { q4_write(data.frame(cell_id = cell, target_id = row$target_id, dgp_id = row$dgp_id, source_sha = q4_head(), conf_status = "profile_failed", profile_engine = "tmbprofile", trace_complete = FALSE, failure_reason = paste0(stage, ": ", conditionMessage(e)), promotion_eligible = FALSE), paths$receipt); stop(e) })
}
if (sys.nframe() == 0L) q4_main()
