#!/usr/bin/env Rscript
if (!requireNamespace("ape", quietly = TRUE) || !requireNamespace("pkgload", quietly = TRUE)) stop("needs ape/pkgload")
mode <- commandArgs(trailingOnly = TRUE); if (!length(mode)) mode <- "--preflight"; if (!mode %in% c("--preflight", "--local")) stop("use --preflight or --local")
out <- "docs/dev-log/evidence/ou-v1-r4"; dir.create(out, recursive = TRUE, showWarnings = FALSE); pkgload::load_all(".", compile = TRUE, quiet = TRUE)
starts <- list(low = list(a = c(.4,.4), s = c(.25,.15)), middle = list(a = c(1,1), s = c(.45,.25)), high = list(a = c(2,2), s = c(.7,.4)))
regimes <- data.frame(regime = c("weak", "separated"), alpha_mu = c(.7,.3), alpha_sigma = c(1.3,2.5), sd_mu = c(.45,.8), sd_sigma = c(.25,.5), seed = c(2026091601L,2026091602L))
payload <- function(r) { set.seed(r$seed); tree <- ape::rcoal(128); tree$tip.label <- sprintf("sp%03d", 1:128); tree$edge.length <- tree$edge.length / max(ape::node.depth.edgelength(tree)[1:128]); d <- ape::cophenetic.phylo(tree); set.seed(r$seed+1L); u <- drop(t(chol(r$sd_mu^2 * exp(-r$alpha_mu*d))) %*% rnorm(128)); set.seed(r$seed+2L); v <- drop(t(chol(r$sd_sigma^2 * exp(-r$alpha_sigma*d))) %*% rnorm(128)); sp <- rep(tree$tip.label, each=12); set.seed(r$seed+3L); list(tree=tree, data=data.frame(y=u[match(sp,tree$tip.label)] + rnorm(length(sp), sd=exp(-1+v[match(sp,tree$tip.label)])),species=sp)) }
fit_one <- function(r,id) { p <- payload(r); tree <- p$tree; f <- bf(y~phylo(1|species,tree=tree,model="ou"), sigma~phylo(1|species,tree=tree,model="ou")); ctl <- drmTMB:::drm_parse_control(drm_control(optimizer=list(eval.max=1500,iter.max=1500))); z <- drmTMB:::drm_build_gaussian_ls_spec(f,p$data,env=environment(),weights=NULL,control=ctl,impute=NULL,missing=drmTMB:::drm_parse_missing_control(miss_control())); s <- starts[[id]]; z$start$beta_mu<-0;z$start$beta_sigma<--1;z$start$log_sd_phylo<-log(s$s);z$start$log_decay_phylo<-log(s$a); w<-character(); t0<-proc.time()[["elapsed"]]; fit<-tryCatch(withCallingHandlers(drmTMB:::drm_fit_spec(z,f,gaussian(),ctl,REML=FALSE,penalty=NULL,estimator="ml"),warning=function(e){w<<-c(w,conditionMessage(e));invokeRestart("muffleWarning")}),error=identity); elapsed<-proc.time()[["elapsed"]]-t0; common<-data.frame(regime=r$regime,start=id,elapsed_seconds=elapsed,warnings=paste(w,collapse=" | "),alpha_mu_truth=r$alpha_mu,alpha_sigma_truth=r$alpha_sigma); if(inherits(fit,"error"))return(cbind(common,status="ERROR",convergence=NA,pdHess=NA,boundary=NA,alpha_mu=NA,alpha_sigma=NA,error=conditionMessage(fit))); a<-unname(fit$decaypars$phylo[c("decay_phylo","decay_phylo:sigma")]); b<-any(a<.02|a>50);cbind(common,status="FIT",convergence=fit$opt$convergence,pdHess=isTRUE(fit$sdr$pdHess),boundary=b,alpha_mu=a[1],alpha_sigma=a[2],error=NA_character_) }
chosen <- if(mode=="--preflight") regimes[1,,drop=FALSE] else regimes; ans <- do.call(rbind,unlist(lapply(seq_len(nrow(chosen)),function(i)lapply(names(starts),function(id)fit_one(chosen[i,,drop=FALSE],id))),recursive=FALSE)); ans$abs_log_error_mu<-abs(log(ans$alpha_mu/ans$alpha_mu_truth));ans$abs_log_error_sigma<-abs(log(ans$alpha_sigma/ans$alpha_sigma_truth)); if(mode=="--preflight"){utils::write.csv(ans,file.path(out,"preflight-attempts.csv"),row.names=FALSE);utils::write.csv(data.frame(projected_seconds=2*sum(ans$elapsed_seconds),within_three_hours=2*sum(ans$elapsed_seconds)<10800),file.path(out,"preflight.csv"),row.names=FALSE);cat("OU_V1_R4_PREFLIGHT_PASS\n")}else{utils::write.csv(ans,file.path(out,"attempts.csv"),row.names=FALSE);cat("OU_V1_R4_LOCAL_PASS\n")}
