#!/usr/bin/env Rscript

write_tsv <- function(x, p) utils::write.table(x, p, sep = "\t", quote = FALSE, row.names = FALSE)
sim_one <- function(seed, tau = .45) {
  set.seed(seed); p1 <- ape::stree(4L, type = "balanced"); p2 <- ape::stree(4L, type = "balanced"); p1$edge.length <- p2$edge.length <- rep(1, nrow(p1$edge)); p1$tip.label <- paste0("plant", 1:4); p2$tip.label <- paste0("poll", 1:4)
  V <- kronecker(drmTMB:::drm_phylo_tip_covariance(p2), drmTMB:::drm_phylo_tip_covariance(p1)); grid <- expand.grid(plant = p1$tip.label, pollinator = p2$tip.label, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE); key <- paste0(grid$plant, ":", grid$pollinator); b <- as.numeric(t(chol(V)) %*% rnorm(nrow(grid), sd = tau)); names(b) <- key
  d <- grid[rep(seq_len(nrow(grid)), each = 40L), , drop = FALSE]; d$x <- rnorm(nrow(d)); k <- paste0(d$plant, ":", d$pollinator); mu <- plogis(-.15 + .35*d$x); sigma <- exp(-1 + b[k]); zoi <- plogis(-1.1); coi <- plogis(.1); boundary <- rbinom(nrow(d), 1, zoi); d$y <- rbeta(nrow(d), mu / sigma^2, (1-mu) / sigma^2); d$y[boundary == 1] <- rbinom(sum(boundary), 1, coi)
  list(data = d, p1 = p1, p2 = p2, b = b, n_zero = sum(d$y == 0), n_one = sum(d$y == 1), min_zero = min(tapply(d$y == 0, k, sum)), min_one = min(tapply(d$y == 1, k, sum)), min_interior = min(tapply(d$y > 0 & d$y < 1, k, sum)))
}
one <- function(seed, sha, md5) {
  s <- sim_one(seed); plant_tree <- s$p1; pollinator_tree <- s$p2; fit <- tryCatch(drmTMB::drmTMB(drmTMB::bf(y ~ x, sigma ~ drmTMB::phylo_interaction(1 | plant:pollinator, tree1 = plant_tree, tree2 = pollinator_tree), zoi ~ 1, coi ~ 1), family = drmTMB::zero_one_beta(), data = s$data, control = drmTMB::drm_control(se=TRUE, optimizer=list(eval.max=2000L, iter.max=2000L))), error = identity)
  if (inherits(fit, "error")) return(data.frame(seed, source_sha=sha, runner_md5=md5,status="fit_error",error=conditionMessage(fit)))
  tau <- unname(fit$sdpars$sigma[["phylo_interaction(1 | plant:pollinator)"]]); mode <- ranef(fit, "phylo_interaction_sigma")$terms[["phylo_interaction(1 | plant:pollinator)"]]
  data.frame(seed, source_sha=sha, runner_md5=md5,status="fit_ok",convergence=fit$opt$convergence,pdHess=isTRUE(fit$sdr$pdHess),max_gradient=max(abs(fit$obj$gr(fit$opt$par))),tau_truth=.45,tau_hat=tau,mode_correlation=cor(mode[names(s$b)],s$b),n_zero=s$n_zero,n_one=s$n_one,min_group_zero=s$min_zero,min_group_one=s$min_one,min_group_interior=s$min_interior,clamp_active=any(abs(fit$obj$report()$log_sigma)>11.99),boundary_hit=!is.finite(tau)||tau<=.05||tau>=2.5)
}
script <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value=TRUE)[1]); root <- normalizePath(file.path(dirname(script),"..")); setwd(root); pkgload::load_all(root,quiet=TRUE,export_all=FALSE); out <- Sys.getenv("DRMTMB_RECOVERY_OUT", unset=file.path(root,"docs/dev-log/implementation-recovery/2026-07-30-lane-c-z7-zob-sigma-phylo-interaction-local-run-1")); dir.create(out,recursive=TRUE,showWarnings=FALSE); sha <- trimws(system2("git",c("rev-parse","HEAD"),stdout=TRUE)); md5 <- unname(tools::md5sum(script)); a <- do.call(rbind,lapply(2026074401:2026074404,one,sha=sha,md5=md5)); write_tsv(a,file.path(out,"raw-attempts.tsv")); ok <- if(all(c("convergence","pdHess","max_gradient","boundary_hit","mode_correlation","min_group_zero","min_group_one","min_group_interior","clamp_active")%in%names(a))) with(a,status=="fit_ok"&convergence==0L&pdHess&max_gradient<=.01&!boundary_hit&!clamp_active&mode_correlation>.45&min_group_zero>0L&min_group_one>0L&min_group_interior>0L) else rep(FALSE,nrow(a)); e <- if(any(ok))mean(abs(a$tau_hat[ok]/.45-1))else NA_real_;write_tsv(data.frame(planned_attempts=4L,attempted_attempts=nrow(a),passed_attempts=sum(ok),mean_tau_relative_error=e,decision=if(all(ok)&&is.finite(e)&&e<=.4)"PASS_POINT_RECOVERY_LOCAL"else"BLOCKED_LOCAL_FIXTURE"),file.path(out,"summary.tsv"))
