#!/usr/bin/env Rscript

write_tsv <- function(x, p) utils::write.table(x, p, sep = "\t", quote = FALSE, row.names = FALSE)
sim_one <- function(seed, tau = .45) {
  set.seed(seed); n <- 32L; each <- 50L; labels <- paste0("site", seq_len(n)); coords <- cbind(seq_len(n), (seq_len(n) %% 5L) / 3); rownames(coords) <- rev(labels)
  K <- exp(-as.matrix(stats::dist(coords)) / stats::median(as.matrix(stats::dist(coords))[as.matrix(stats::dist(coords)) > 0])); diag(K) <- diag(K) + 1e-6; b <- as.numeric(t(chol(K)) %*% rnorm(n, sd = tau)); names(b) <- labels
  site <- rep(labels, each = each); x <- rnorm(length(site)); mu <- plogis(-.15 + .35 * x); sigma <- exp(-1 + b[site]); zoi <- plogis(-1.1); coi <- plogis(.1); boundary <- rbinom(length(x), 1, zoi); y <- rbeta(length(x), mu / sigma^2, (1 - mu) / sigma^2); y[boundary == 1] <- rbinom(sum(boundary), 1, coi)
  list(data = data.frame(y, x, site), coords = coords, b = b, n_zero = sum(y == 0), n_one = sum(y == 1), min_zero = min(tapply(y == 0, site, sum)), min_one = min(tapply(y == 1, site, sum)), min_interior = min(tapply(y > 0 & y < 1, site, sum)))
}
one <- function(seed, sha, md5) {
  s <- sim_one(seed); coords <- s$coords; fit <- tryCatch(drmTMB::drmTMB(drmTMB::bf(y ~ x, sigma ~ drmTMB::spatial(1 | site, coords = coords), zoi ~ 1, coi ~ 1), family = drmTMB::zero_one_beta(), data = s$data, control = drmTMB::drm_control(se = TRUE, optimizer = list(eval.max = 2000L, iter.max = 2000L))), error = identity)
  if (inherits(fit, "error")) return(data.frame(seed, source_sha = sha, runner_md5 = md5, status = "fit_error", error = conditionMessage(fit)))
  tau <- unname(fit$sdpars$sigma[["spatial(1 | site)"]]); mode <- ranef(fit, "spatial_sigma")$terms[["spatial(1 | site)"]]
  data.frame(seed, source_sha = sha, runner_md5 = md5, status = "fit_ok", convergence = fit$opt$convergence, pdHess = isTRUE(fit$sdr$pdHess), max_gradient = max(abs(fit$obj$gr(fit$opt$par))), tau_truth = .45, tau_hat = tau, mode_correlation = cor(mode[names(s$b)], s$b), n_zero = s$n_zero, n_one = s$n_one, min_group_zero = s$min_zero, min_group_one = s$min_one, min_group_interior = s$min_interior, clamp_active = any(abs(fit$obj$report()$log_sigma) > 11.99), boundary_hit = !is.finite(tau) || tau <= .05 || tau >= 2.5)
}
script <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]); root <- normalizePath(file.path(dirname(script), "..")); setwd(root); pkgload::load_all(root, quiet = TRUE, export_all = FALSE); out <- Sys.getenv("DRMTMB_RECOVERY_OUT", unset = file.path(root, "docs/dev-log/implementation-recovery/2026-07-30-lane-c-z7-zob-sigma-spatial-local-run-1")); dir.create(out, recursive = TRUE, showWarnings = FALSE); sha <- trimws(system2("git", c("rev-parse", "HEAD"), stdout = TRUE)); md5 <- unname(tools::md5sum(script))
a <- do.call(rbind, lapply(2026074301:2026074304, one, sha = sha, md5 = md5)); write_tsv(a, file.path(out, "raw-attempts.tsv")); ok <- if (all(c("convergence", "pdHess", "max_gradient", "boundary_hit", "mode_correlation", "min_group_zero", "min_group_one", "min_group_interior", "clamp_active") %in% names(a))) with(a, status == "fit_ok" & convergence == 0L & pdHess & max_gradient <= .01 & !boundary_hit & !clamp_active & mode_correlation > .45 & min_group_zero > 0L & min_group_one > 0L & min_group_interior > 0L) else rep(FALSE, nrow(a)); err <- if (any(ok)) mean(abs(a$tau_hat[ok] / .45 - 1)) else NA_real_; write_tsv(data.frame(planned_attempts = 4L, attempted_attempts = nrow(a), passed_attempts = sum(ok), mean_tau_relative_error = err, decision = if (all(ok) && is.finite(err) && err <= .4) "PASS_POINT_RECOVERY_LOCAL" else "BLOCKED_LOCAL_FIXTURE"), file.path(out, "summary.tsv"))
