#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly=TRUE); if(length(args)) stop('No arguments.', call.=FALSE)
root <- normalizePath('.', mustWork=TRUE); pkgload::load_all(root, compile=TRUE, quiet=TRUE)
out <- Sys.getenv('DRMTMB_TEMPORAL_HOMTOEP_PROFILE_PRERUN_OUT', unset=file.path(root,'docs/dev-log/simulation-artifacts/2026-09-10-temporal-homtoep-marginal-profile-prerun-v1'))
dir.create(out,recursive=TRUE,showWarnings=FALSE); needed <- c('results.csv','provenance.csv','RESULTS.md','session-info.txt')
if(any(file.exists(file.path(out,needed)))) stop('Evidence exists; do not overwrite.',call.=FALSE)
rho <- list(P1=c(1,.55^(1:5)),P2=drmTMB:::temporal_homtoep_correlations(c(atanh(.45),atanh(-.3),atanh(.2),atanh(.1),atanh(-.05))),P3=drmTMB:::temporal_homtoep_correlations(c(atanh(-.45),atanh(.15),atanh(-.1),atanh(.05),0)))
conditions <- expand.grid(cell=names(rho),replicate=1:5,KEEP.OUT.ATTRS=FALSE,stringsAsFactors=FALSE); conditions$seed <- 2026091400L+seq_len(nrow(conditions))
sim <- function(cell,seed){set.seed(seed); n<-80L; k<-6L; id<-factor(rep(sprintf('id_%03d',1:n),each=k)); occasion<-rep(0:5,n); between<-rep(rep(c(-.5,.5),length.out=n),each=k); within<-unlist(lapply(1:n,function(i)sample(rep(c(-.5,.5),length.out=k))),use.names=FALSE); e<-unlist(lapply(1:n,function(i)as.vector(.8*t(chol(toeplitz(rho[[cell]])))%*%rnorm(k))),use.names=FALSE); data.frame(y=.5*between+.5*within+e,id,occasion,between,within)}
rows<-lapply(seq_len(nrow(conditions)),function(i){z<-conditions[i,]; started<-proc.time()[['elapsed']]; ans<-tryCatch({fit<-drmTMB::drmTMB(drmTMB::bf(y~between+within+temporal(1|id,time=occasion,structure='homtoep'),sigma~1),data=sim(z$cell,z$seed),family=gaussian(),REML=FALSE); ci<-drmTMB:::drm_profile_confint(fit,parm=c('fixef:mu:(Intercept)','fixef:mu:between','fixef:mu:within'),level=.95,profile_engine='tmbprofile',profile_precision='fast',profile_maxit=50L); list(ok=TRUE,ci=ci,error='')},error=function(e)list(ok=FALSE,ci=NULL,error=conditionMessage(e))); elapsed<-proc.time()[['elapsed']]-started; data.frame(cell=z$cell,replicate=z$replicate,seed=z$seed,ok=ans$ok,elapsed_sec=elapsed,n_intervals=if(ans$ok)nrow(ans$ci)else 0L,all_finite=if(ans$ok)all(is.finite(ans$ci$lower)&is.finite(ans$ci$upper))else FALSE,error=ans$error)})
results<-do.call(rbind,rows); write.csv(results,file.path(out,'results.csv'),row.names=FALSE); prov<-data.frame(key=c('source_commit','runner_md5','run_utc','n_fixtures'),value=c(system2('git',c('rev-parse','HEAD'),stdout=TRUE),unname(tools::md5sum('tools/run-temporal-homtoep-marginal-profile-prerun.R')),format(Sys.time(),tz='UTC',usetz=TRUE),nrow(results)));write.csv(prov,file.path(out,'provenance.csv'),row.names=FALSE);writeLines(c('# Marginal Toeplitz profile pre-run','','Fifteen frozen profiles: five seeds in each primary cell. This measures profile endpoint availability and runtime only.'),file.path(out,'RESULTS.md'));capture.output(sessionInfo(),file=file.path(out,'session-info.txt'));if(!all(results$ok&results$all_finite&results$n_intervals==3L))stop('Pre-run profile completeness failed; outputs retained.',call.=FALSE);cat('TEMPORAL_HOMTOEP_PROFILE_PRERUN_PASS\n')
