#!/usr/bin/env Rscript
# Retained two-target profile gate for fixed bivariate Gaussian residual scales.
bfs_stop <- function(...) stop(..., call. = FALSE)
bfs_file <- grep("^--file=", commandArgs(FALSE), value = TRUE); bfs_script <- normalizePath(if (length(bfs_file)) sub("^--file=", "", bfs_file[[1L]]) else "tools/run-lane-b-biv-fixed-scale-profile-gate.R", mustWork = FALSE); bfs_root <- normalizePath(file.path(dirname(bfs_script), ".."), mustWork = TRUE)
bfs_hash <- function(p) { cmd <- if (nzchar(Sys.which("sha256sum"))) "sha256sum" else "shasum"; z <- system2(cmd, if (identical(cmd, "sha256sum")) p else c("-a", "256", p), stdout = TRUE, stderr = TRUE); if (!length(z) || !grepl("^[0-9a-f]{64}\\s", z[[1L]])) bfs_stop("Cannot hash ", p); sub("\\s.*$", "", z[[1L]]) }
bfs_head <- function() paste(system2("git", c("-C", bfs_root, "rev-parse", "HEAD"), stdout = TRUE), collapse = "")
bfs_write <- function(x, p) { dir.create(dirname(p), recursive = TRUE, showWarnings = FALSE); utils::write.table(x, p, sep = "\t", quote = FALSE, row.names = FALSE, na = "") }
bfs_main <- function(args = commandArgs(trailingOnly = TRUE)) {
  if (identical(args, "--dry-run")) { e <- new.env(parent = baseenv()); sys.source(file.path(bfs_root, "tools", "validate-lane-b-biv-fixed-scale-contracts.R"), e); e$lane_b_biv_fixed_scale_validate(bfs_root); return(invisible(TRUE)) }
  v <- as.list(sub("^[^=]+=", "", args)); names(v) <- sub("^--([^=]+)=.*$", "\\1", args); req <- c("cell", "seed", "rung", "output-dir", "goal-authorized"); if (!setequal(names(v), req) || !identical(v[["goal-authorized"]], "lane-b-144-goal")) bfs_stop("Requires exact --cell, --seed, --rung, --output-dir, and --goal-authorized=lane-b-144-goal.")
  e <- new.env(parent = baseenv()); sys.source(file.path(bfs_root, "tools", "validate-lane-b-biv-fixed-scale-contracts.R"), e); registry <- e$lane_b_biv_fixed_scale_validate(bfs_root); cell <- v$cell; row <- registry[registry$cell_id == cell, , drop = FALSE]; if (nrow(row) != 1L || !identical(as.integer(v$seed), 3L) || !identical(v$rung, "high")) bfs_stop("Only exact high-rung fixed-scale targets are executable.")
  expected <- file.path(bfs_root, "docs", "dev-log", "interval-feasibility", "results", bfs_head(), "biv-fixed-scale", cell); if (!identical(normalizePath(v[["output-dir"]], mustWork = FALSE), normalizePath(expected, mustWork = FALSE))) bfs_stop("--output-dir must be the exact source-SHA receipt path.")
  stem <- sprintf("lane-b-biv-fixed-scale-profile-%s-high-seed-3", cell); paths <- setNames(file.path(v[["output-dir"]], paste0(stem, c("-trace.tsv", "-interval.tsv", "-receipt.tsv"))), c("trace", "interval", "receipt")); if (any(file.exists(paths))) bfs_stop("Refusing to replace retained artifact.")
  stage <- "adapter"; tryCatch({
    a <- new.env(parent = globalenv()); sys.source(file.path(bfs_root, "tools", "lane-b-biv-fixed-scale-adapters.R"), a); fx <- a$lane_b_biv_fixed_scale_fixture(cell, as.integer(v$seed), v$rung); if (!identical(fx$truth$profile_parameter, row$profile_parameter[[1L]]) || !identical(fx$truth$dgp_id, row$dgp_id[[1L]])) bfs_stop("Adapter differs from frozen contract.")
    stage <- "load"; pkgload::load_all(bfs_root, quiet = TRUE, export_all = FALSE); stage <- "fit"; fit <- fx$fit(fx$data); target <- row$profile_parameter[[1L]]; if (nrow(drmTMB::profile_targets(fit)[drmTMB::profile_targets(fit)$parm == target & drmTMB::profile_targets(fit)$profile_ready %in% TRUE, , drop = FALSE]) != 1L) bfs_stop("Target is not uniquely profile-ready.")
    stage <- "profile"; trace <- as.data.frame(stats::profile(fit, parm = target, trace = TRUE), stringsAsFactors = FALSE); one <- function(nm) { z <- unique(trace[[nm]]); if (!length(z) || length(z) != 1L) bfs_stop("Trace lacks unique ", nm); z[[1L]] }; status <- as.character(one("conf.status")); msg <- as.character(one("profile.message")); lo <- as.numeric(one("conf.low")); hi <- as.numeric(one("conf.high")); est <- as.numeric(one("estimate")); di <- drmTMB:::profile_interval_diagnostics(c(lo, hi), transformation = as.character(one("transformation")), estimate = est); complete <- identical(status, "profile") && identical(msg, "ok"); pass <- complete && !isTRUE(di$boundary) && !identical(status, "clamp_limited") && all(is.finite(c(est, lo, hi))) && lo < hi && est >= lo && est <= hi && fit$opt$convergence == 0L && isTRUE(fit$sdr$pdHess)
    trace$cell_id <- cell; trace$target_id <- row$target_id; trace$seed <- 3L; trace$execution_information_rung <- "high"; interval <- data.frame(cell_id = cell, target_id = row$target_id, dgp_id = row$dgp_id, seed = 3L, lower = lo, upper = hi, profile_engine = "tmbprofile"); bfs_write(trace, paths[["trace"]]); bfs_write(interval, paths[["interval"]]); receipt <- data.frame(cell_id = cell, target_id = row$target_id, dgp_id = row$dgp_id, dgp_version = row$dgp_version, formula = row$formula, true_parameter_scale = row$true_parameter_scale, profile_parameter = target, seed = 3L, execution_information_rung = "high", source_sha = bfs_head(), recorded_at = format(Sys.time(), tz = "UTC", usetz = TRUE), conf_status = if (pass) "profile" else "profile_failed", profile_engine = "tmbprofile", estimate = est, lower = if (pass) lo else NA_real_, upper = if (pass) hi else NA_real_, convergence = as.integer(fit$opt$convergence), pdHess = isTRUE(fit$sdr$pdHess), profile_boundary = isTRUE(di$boundary), clamp_limited = identical(status, "clamp_limited"), trace_complete = complete, failure_reason = if (pass) NA_character_ else if (isTRUE(di$boundary)) di$message else msg, promotion_eligible = FALSE, runner_sha256 = bfs_hash(bfs_script), adapter_sha256 = bfs_hash(file.path(bfs_root, "tools", "lane-b-biv-fixed-scale-adapters.R")), trace_path = normalizePath(paths[["trace"]], mustWork = TRUE), interval_path = normalizePath(paths[["interval"]], mustWork = TRUE), trace_sha256 = bfs_hash(paths[["trace"]]), interval_sha256 = bfs_hash(paths[["interval"]]), stringsAsFactors = FALSE); bfs_write(receipt, paths[["receipt"]]); message("Fixed-scale receipt: ", cell, " / ", receipt$conf_status)
  }, error = function(err) { bfs_write(data.frame(cell_id = cell, target_id = row$target_id, dgp_id = row$dgp_id, source_sha = bfs_head(), conf_status = "profile_failed", profile_engine = "tmbprofile", trace_complete = FALSE, failure_reason = paste0(stage, ": ", conditionMessage(err)), promotion_eligible = FALSE), paths[["receipt"]]); stop(err) })
}
if (sys.nframe() == 0L) bfs_main()
