#!/usr/bin/env Rscript
if (!requireNamespace("ape", quietly = TRUE) || !requireNamespace("pkgload", quietly = TRUE)) stop("needs ape/pkgload")
mode <- commandArgs(trailingOnly = TRUE); preflight <- identical(mode, "--preflight")
out <- "docs/dev-log/evidence/ou-v1-r33"; dir.create(out, recursive = TRUE, showWarnings = FALSE)
pkgload::load_all(".", compile = TRUE, quiet = TRUE)
set.seed(2026091401); tree <- ape::rcoal(3); tree$tip.label <- paste0("sp", 1:3); tree$edge.length <- tree$edge.length / max(ape::node.depth.edgelength(tree)[1:3])
d <- ape::cophenetic.phylo(tree); u <- drop(t(chol(.45^2 * exp(-.7 * d))) %*% rnorm(3)); v <- drop(t(chol(.25^2 * exp(-1.3 * d))) %*% rnorm(3)); species <- rep(tree$tip.label, each = 3); ii <- match(species, tree$tip.label); dat <- data.frame(y = u[ii] + rnorm(9, sd = exp(-1 + v[ii])), species = species)
rate <- list(interior = c(.7, 1.3), ridge = c(8, 8)); amp <- list(interior = c(.45, .25), ridge = c(.19, .057))
fit_point <- function(a, s) { f <- bf(y ~ phylo(1 | species, tree = tree, model = "ou"), sigma ~ phylo(1 | species, tree = tree, model = "ou")); ctl <- drmTMB:::drm_parse_control(drm_control()); z <- drmTMB:::drm_build_gaussian_ls_spec(f, dat, env = environment(), weights = NULL, control = ctl, impute = NULL, missing = drmTMB:::drm_parse_missing_control(miss_control())); z$map$log_decay_phylo <- factor(c(NA, NA)); z$start$log_decay_phylo <- log(a); z$map$log_sd_phylo <- factor(c(NA, NA)); z$start$log_sd_phylo <- log(s); drmTMB:::drm_fit_spec(z, f, gaussian(), ctl, REML = FALSE, penalty = NULL, estimator = "ml") }
log_sum_exp <- function(x) { m <- max(x); m + log(sum(exp(x - m))) }
run_cell <- function(rate_id, amp_id, batches, draws, seed) {
  fit <- suppressWarnings(fit_point(rate[[rate_id]], amp[[amp_id]])); mu <- unname(fit$par$mu[[1]]); ls <- unname(fit$par$sigma[[1]])
  L1 <- t(chol(amp[[amp_id]][1]^2 * exp(-rate[[rate_id]][1] * d))); L2 <- t(chol(amp[[amp_id]][2]^2 * exp(-rate[[rate_id]][2] * d)))
  logtarget <- function(w) { W <- as.matrix(w); if (is.null(dim(w))) W <- matrix(w, nrow = 1); x <- W[, 1:3, drop = FALSE] %*% L1; z <- W[, 4:6, drop = FALSE] %*% L2; ans <- rowSums(dnorm(W, log = TRUE)); for (j in seq_len(nrow(dat))) ans <- ans + dnorm(dat$y[j], mu + x[, ii[j]], exp(ls + z[, ii[j]]), log = TRUE); ans }
  opt <- optim(rep(0, 6), function(w) -logtarget(w), method = "BFGS", hessian = TRUE, control = list(reltol = 1e-12)); ee <- eigen((opt$hessian + t(opt$hessian)) / 2, symmetric = TRUE); floor <- max(1e-6, max(ee$values) * 1e-8); vals <- pmax(ee$values, floor); cov <- 1.5 * ee$vectors %*% diag(1 / vals) %*% t(ee$vectors); cc <- chol(cov); logdet <- 2 * sum(log(diag(cc)))
  set.seed(seed); rows <- lapply(seq_len(batches), function(b) { W <- sweep(matrix(rnorm(draws * 6), ncol = 6) %*% cc, 2, opt$par, "+"); centered <- sweep(W, 2, opt$par, "-"); q <- -.5 * (6 * log(2 * pi) + logdet + rowSums((centered %*% solve(cov)) * centered)); lw <- logtarget(W) - q; lz <- log_sum_exp(lw) - log(draws); ess <- exp(2 * log_sum_exp(lw) - log_sum_exp(2 * lw)); data.frame(batch = b, nll = -lz, ess = ess) })
  b <- do.call(rbind, rows); data.frame(rate_id = rate_id, amplitude_id = amp_id, laplace = fit$opt$objective, mode_convergence = opt$convergence, min_hessian_eigen = min(ee$values), proposal_floor = floor, batches = batches, draws_per_batch = draws, nll_mean = mean(b$nll), nll_se = sd(b$nll) / sqrt(batches), min_ess = min(b$ess), stringsAsFactors = FALSE) |> cbind(batch_nll_1 = b$nll[1], batch_nll_2 = b$nll[2], batch_nll_3 = b$nll[3], batch_nll_4 = b$nll[4], batch_nll_5 = if (batches >= 5) b$nll[5] else NA_real_, batch_nll_6 = if (batches >= 6) b$nll[6] else NA_real_, batch_nll_7 = if (batches >= 7) b$nll[7] else NA_real_, batch_nll_8 = if (batches >= 8) b$nll[8] else NA_real_)
}
if (preflight) { t0 <- proc.time()[["elapsed"]]; x <- run_cell("ridge", "interior", 4, 500, 2026091501); elapsed <- proc.time()[["elapsed"]] - t0; x$elapsed_seconds <- elapsed; x$projected_full_seconds <- elapsed * 16; utils::write.csv(x, file.path(out, "preflight.csv"), row.names = FALSE); cat("OU_V1_R33_PREFLIGHT_PASS\n") } else { x <- rbind(run_cell("ridge", "interior", 8, 2000, 2026091502), run_cell("interior", "interior", 8, 2000, 2026091503)); utils::write.csv(x, file.path(out, "reference.csv"), row.names = FALSE); ape::write.tree(tree, file.path(out, "tree.nwk")); utils::write.csv(dat, file.path(out, "data.csv"), row.names = FALSE); cat("OU_V1_R33_RUN_PASS\n") }
