#!/usr/bin/env Rscript
# THE CAPABILITY-STATUS JOIN as a generated artefact (parity-joint A11
# preparation, 2026-09-05).
#
# Joins the two twins' `docs/design/capability-status.md` files by row name and
# reports the three things a closure has to know and cannot get anywhere else:
#
#   1. rows present in drmTMB's file and NOT in DRM.jl's;
#   2. rows present in DRM.jl's file and NOT in drmTMB's;
#   3. rows present in both whose STATUS WORD differs.
#
# WHY THIS IS NOT `docs/design/parity-matrix.md`'s job. The matrix ABORTS when a
# drmTMB capability name is missing from DRM.jl's file -- that guard is right
# for the matrix, which must not emit a half-joined row, but it means the matrix
# can never report case (1). This file exists to report exactly the cases the
# matrix refuses to render. It never aborts on an unmatched row; an unmatched
# row is its output.
#
# HOW DRM.jl IS READ. With `git show <pin>:<path>` against a DRM.jl repository,
# never its working tree -- the canonical clone routinely sits on some other
# lane's branch, and reading that would silently report another agent's
# in-flight edit as the state of main. The pin is the programme pin
# (docs/dev-log/loop/parity-joint-20260905/source-pins.json repins[-1]),
# read and verified through `tools/parity-pin.R` (S1b, amendment A8) -- the
# SAME pin `write-parity-matrix.R` and `write-parity-scoreboard.R` read, so
# this file can never quietly compare against a different DRModels commit
# than the other two. Before S1b this file instead read a caller-selectable
# git ref (default `origin/main`, overridable by an environment variable);
# that let it drift from the pin the rest of the ledger is honest against,
# which is exactly what one read path exists to prevent.
#
# The parser is the matrix generator's `pm_parse_status_table()`, reached by
# `sys.source()`. One parser, so the row set here and the row set in the matrix
# and the scoreboard can never drift apart.
#
# USAGE (from the drmTMB source checkout; no Julia is started):
#   DRM_JL_REPO=/path/to/DRM.jl Rscript tools/write-capability-status-join.R
#   Rscript tools/write-capability-status-join.R <drmjl-repo> [<out>]
#
# Both shas -- drmTMB's HEAD and the programme pin -- are written into the
# output. Running this twice at the same two commits yields byte-identical
# output.

csj_matrix_env <- function(root) {
  path <- file.path(root, "tools", "write-parity-matrix.R")
  if (!file.exists(path)) {
    stop("tools/write-parity-matrix.R not found under ", root, call. = FALSE)
  }
  env <- new.env(parent = globalenv())
  # sys.source() runs inside this call, so the generator's
  # `if (sys.nframe() == 0L) main()` guard does not fire.
  sys.source(path, envir = env)
  env
}

csj_git <- function(repo, ...) {
  out <- suppressWarnings(system2(
    "git", c("-C", shQuote(repo), ...), stdout = TRUE, stderr = FALSE
  ))
  status <- attr(out, "status")
  if (!is.null(status) && status != 0L) {
    stop("git ", paste(c(...), collapse = " "), " failed in ", repo, call. = FALSE)
  }
  as.character(out)
}

csj_build <- function(root, drmjl_repo) {
  env <- csj_matrix_env(root)
  # ONE READ PATH for the DRModels pin (S1b, amendment A8): tools/parity-pin.R,
  # loaded transitively through write-parity-matrix.R's pm_pin_env(). Refuses
  # `drmjl_repo` outright when its HEAD is not the programme pin, rather than
  # reading and reporting on whatever commit it happens to be on.
  pin_env <- env$pm_pin_env(root)
  path <- "docs/design/capability-status.md"

  drmtmb_sha <- pin_env$pp_git_rev_parse(root)
  drmjl_sha <- pin_env$pp_verify_pin(drmjl_repo, root = root)

  r_lines <- readLines(file.path(root, path), warn = FALSE, encoding = "UTF-8")
  j_lines <- csj_git(drmjl_repo, "show", shQuote(paste0(drmjl_sha, ":", path)))

  r <- env$pm_parse_status_table(r_lines)
  j <- env$pm_parse_status_table(j_lines)

  only_r <- r[!r$capability %in% j$capability, , drop = FALSE]
  only_j <- j[!j$capability %in% r$capability, , drop = FALSE]

  both <- merge(r, j, by = "capability", suffixes = c("_r", "_j"))
  both <- both[order(both$line_r), , drop = FALSE]
  differing <- both[both$status_r != both$status_j, , drop = FALSE]

  list(path = path, drmtmb_sha = drmtmb_sha, drmjl_sha = drmjl_sha,
       r = r, j = j, only_r = only_r, only_j = only_j,
       both = both, differing = differing, env = env)
}

csj_render <- function(x) {
  name_cell <- function(v) vapply(v, function(s) {
    if (grepl("`", s, fixed = TRUE)) s else paste0("`", s, "`")
  }, character(1L), USE.NAMES = FALSE)
  r_cite <- function(line) sprintf("%s:%d", x$path, line)
  j_cite <- function(line) sprintf("DRM.jl@%s:%s:%d", substr(x$drmjl_sha, 1L, 8L), x$path, line)

  c(
    "# drmTMB <-> DRM.jl capability-status join",
    "",
    "GENERATED by `tools/write-capability-status-join.R` -- do not edit by hand.",
    "Regenerate with",
    "`DRM_JL_REPO=<DRM.jl repo> Rscript tools/write-capability-status-join.R`",
    "from the drmTMB source checkout (no Julia is started).",
    "",
    "## What this file was generated against",
    "",
    "| input | sha |",
    "|---|---|",
    sprintf("| drmTMB (this repo, HEAD at generation) | `%s` |", x$drmtmb_sha),
    sprintf("| DRM.jl, at the programme pin, read with `git show` -- never its working tree | `%s` |",
            x$drmjl_sha),
    "",
    "The canonical DRM.jl clone normally sits on some lane's branch. Reading its",
    "working tree would report that lane's in-flight edit as the state of main, so",
    "this file reads the programme pin (docs/dev-log/loop/parity-joint-20260905/source-pins.json",
    "repins[-1], via tools/parity-pin.R) and refuses a checkout on any other commit.",
    "",
    "## Counts",
    "",
    "| | count |",
    "|---|---:|",
    sprintf("| rows in drmTMB's `%s` | %d |", x$path, nrow(x$r)),
    sprintf("| rows in DRM.jl's `%s` | %d |", x$path, nrow(x$j)),
    sprintf("| matched byte-for-byte on the row name | %d |", nrow(x$both)),
    sprintf("| **present only in drmTMB's file** | **%d** |", nrow(x$only_r)),
    sprintf("| **present only in DRM.jl's file** | **%d** |", nrow(x$only_j)),
    sprintf("| matched but the status WORD differs | %d |", nrow(x$differing)),
    "",
    "## Rows only in drmTMB's file",
    "",
    "A capability drmTMB names and DRM.jl does not. `tools/write-parity-matrix.R`",
    "ABORTS on this case rather than emit a half-joined row, so the matrix cannot",
    "show it and this list is the only place it appears.",
    "",
    if (nrow(x$only_r)) {
      sprintf("- %s -- `%s` (%s)", name_cell(x$only_r$capability), x$only_r$status,
              r_cite(x$only_r$line))
    } else {
      "None. Every drmTMB row name exists byte-for-byte in DRM.jl's file."
    },
    "",
    "## Rows only in DRM.jl's file",
    "",
    "A capability the Julia twin names and drmTMB does not. These are not gaps in",
    "drmTMB by themselves -- an estimator or metric with no R counterpart is a",
    "legitimate Julia-only row -- but each one is a claim the joint closure has to",
    "either mirror or explicitly decline.",
    "",
    if (nrow(x$only_j)) {
      sprintf("- %s -- `%s` (%s)", name_cell(x$only_j$capability), x$only_j$status,
              j_cite(x$only_j$line))
    } else {
      "None. Every DRM.jl row name exists byte-for-byte in drmTMB's file."
    },
    "",
    "## Matched rows whose status word differs",
    "",
    "Same capability name, different status word. Each row is a disagreement",
    "between the twins that a closure statement would otherwise average away.",
    "",
    if (nrow(x$differing)) {
      c("| capability | drmTMB | DRM.jl |",
        "|---|---|---|",
        sprintf("| %s | `%s` (%s) | `%s` (%s) |",
                name_cell(x$differing$capability),
                x$differing$status_r, r_cite(x$differing$line_r),
                x$differing$status_j, j_cite(x$differing$line_j)))
    } else {
      "None: every matched row carries the same status word on both sides."
    },
    "",
    "## What this file does NOT claim",
    "",
    "- A matched row name means the two files USE THE SAME WORDS, not that the two",
    "  implementations cover the same cells. `docs/design/parity-matrix.md` and",
    "  `docs/design/parity-scoreboard.md` are where a matched name is tested",
    "  against evidence.",
    "- A status word is each twin's own projection of its own cell census. When a",
    "  status word and that twin's census disagree, the census wins.",
    "- Nothing here says anything about `engine = \"julia\"`. Both columns are",
    "  NATIVE status."
  )
}

csj_write <- function(root, drmjl_repo,
                      out = file.path(root, "docs", "design", "capability-status-join.md")) {
  x <- csj_build(root, drmjl_repo)
  lines <- csj_render(x)
  dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, out, useBytes = TRUE)
  message("wrote capability-status join to ", out, ": ", nrow(x$r), " drmTMB rows, ",
          nrow(x$j), " DRM.jl rows, ", nrow(x$only_r), " drmTMB-only, ",
          nrow(x$only_j), " DRM.jl-only, ", nrow(x$differing), " status disagreements")
  invisible(x)
}

main <- function() {
  args <- commandArgs(trailingOnly = TRUE)
  repo <- if (length(args) >= 1L) args[[1L]] else Sys.getenv("DRM_JL_REPO", unset = "")
  if (!nzchar(repo) || !dir.exists(repo)) {
    stop("Set DRM_JL_REPO (or pass it as the first argument) to a DRM.jl repository.",
         call. = FALSE)
  }
  out <- if (length(args) >= 2L) args[[2L]] else file.path("docs", "design", "capability-status-join.md")
  csj_write(".", repo, out)
}

if (sys.nframe() == 0L) {
  main()
}
